--- 
title: "Statistical Methods"
author: "Post, Avery, Osborne"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "Applied statistical methods book."
---

# Introduction  

## About the book  

The goal in creating this book is to provide a thorough treatment of applied statistical methodologies geared toward analyzing designed experiments. Our approach emphasizes the problems researchers encounter rather than provide a litany of solutions with only modest context. We discuss a real scientific problem, thoughfully consider the data that could be used to answer that problem, investigate experimental designs that would be useful, and pursue statistical models to make informed decisions in the context of how the data was collected. The focus of the book is on the statistical modeling portion but problems are viewed holistically. We purposefully introduce the linear model framework in matrix form early on and place most of the methodologies under that umbrella. This helps the reader to see the methods as a part of a general framework as opposed to a set of tools within a toolbox. We believe that the book should be appropriate for a graduate level student that has some comfort in mathematics, particularly linear algebra. Both SAS and R are used throughout to make sure the book works for a wide audience of practitioners.


## Software  

We'll use software throughout the book and include a section on both R and SAS in each chapter.  The following sections give a brief introduction to each software that should prepare you for what's ahead.  

### R  

Section designed to demonstrate basic use of R via R Studio. By the end of this section students will be able to:

    read, write, and explain the steps and purpose of R programs
    efficiently read in and manipulate data in R
    utilize R help and other resources to customize programs
    produce and interpret numerical and graphical summaries using R

Topics

    About R

    R as a calculator

    OOB programming and methods

    common data objects in R
        Vectors, Lists, Matrices, Data Frames

    Subsetting vectors, matrices, data frames, and lists


Module 2 - Markdown (very brief)

    Notebook environment
    Three elements of markdown documents
    Markdown syntax
    Code chunks and options
    Creating different output types

Module 3 - Reading in External Data
Topics

    Delimiters and common data formats
    R Packages and the tidyverse
    Databases
    SQL

Module 4 - Manipulating Data
Topics

    dplyr
    logical statements
    creating new variables

### SAS

Section designed to demonstrate basic use of SAS via SAS Studio. By the end of this section students will be able to:

    write basic SAS programs in SAS Studio using SAS University edition
    import well formatted data into SAS using the import wizard, PROC IMPORT, or a DATA step
    create common numerical and graphical summaries of data
    understand the capabilities of SAS program (something like this but a little clearer maybe)


SAS Programming
Topics

    Common elements of SAS programs: PROC and DATA steps
    Steps, statements, keywords, and options
    SAS windows
    Submitting SAS code, checking logs, and viewing output
    GPP elements

Module 2 - Importing Data
Topics

    SAS library
    Data set names (one vs two level)
    Methods for importing data: Instream, Import Wizard, and Data step
    Delimiters and common data formats
    Types of variables in SAS
    Explorer and PROC PRINT/CONTENTS for investigating a SAS data set


Module 3 - Manipulating Data
Topics

    very basic stuff