<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Summarizing Data | Statistical Methods</title>
  <meta name="description" content="Applied statistical methods book." />
  <meta name="generator" content="bookdown 0.17.2 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Summarizing Data | Statistical Methods" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Applied statistical methods book." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Summarizing Data | Statistical Methods" />
  
  <meta name="twitter:description" content="Applied statistical methods book." />
  

<meta name="author" content="Post, Avery, Osborne" />


<meta name="date" content="2020-04-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="sampling-schemes-and-experimental-design.html"/>
<link rel="next" href="point-estimates.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#about-the-book"><i class="fa fa-check"></i><b>1.1</b> About the book</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#software"><i class="fa fa-check"></i><b>1.2</b> Software</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#r"><i class="fa fa-check"></i><b>1.3</b> R</a><ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>1.3.1</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="1.3.2" data-path="index.html"><a href="index.html#using-rstudio"><i class="fa fa-check"></i><b>1.3.2</b> Using RStudio</a></li>
<li class="chapter" data-level="1.3.3" data-path="index.html"><a href="index.html#r-objects-and-classes"><i class="fa fa-check"></i><b>1.3.3</b> R Objects and Classes</a></li>
<li class="chapter" data-level="1.3.4" data-path="index.html"><a href="index.html#data-objects"><i class="fa fa-check"></i><b>1.3.4</b> Data Objects</a></li>
<li class="chapter" data-level="1.3.5" data-path="index.html"><a href="index.html#accessing-common-data-objects"><i class="fa fa-check"></i><b>1.3.5</b> Accessing Common Data Objects</a></li>
<li class="chapter" data-level="1.3.6" data-path="index.html"><a href="index.html#basics-of-r-recap"><i class="fa fa-check"></i><b>1.3.6</b> Basics of R Recap</a></li>
<li class="chapter" data-level="1.3.7" data-path="index.html"><a href="index.html#reading-data-basics"><i class="fa fa-check"></i><b>1.3.7</b> Reading Data Basics</a></li>
<li class="chapter" data-level="1.3.8" data-path="index.html"><a href="index.html#quick-aside-rstudio-project"><i class="fa fa-check"></i><b>1.3.8</b> Quick Aside: RStudio Project</a></li>
<li class="chapter" data-level="1.3.9" data-path="index.html"><a href="index.html#quick-aside-factors"><i class="fa fa-check"></i><b>1.3.9</b> Quick Aside: Factors</a></li>
<li class="chapter" data-level="1.3.10" data-path="index.html"><a href="index.html#quick-aside-r-packages"><i class="fa fa-check"></i><b>1.3.10</b> Quick Aside: R Packages</a></li>
<li class="chapter" data-level="1.3.11" data-path="index.html"><a href="index.html#reading-delimited-data"><i class="fa fa-check"></i><b>1.3.11</b> Reading Delimited Data</a></li>
<li class="chapter" data-level="1.3.12" data-path="index.html"><a href="index.html#excel-data"><i class="fa fa-check"></i><b>1.3.12</b> Excel data</a></li>
<li class="chapter" data-level="1.3.13" data-path="index.html"><a href="index.html#sas-data"><i class="fa fa-check"></i><b>1.3.13</b> SAS Data</a></li>
<li class="chapter" data-level="1.3.14" data-path="index.html"><a href="index.html#spss-data"><i class="fa fa-check"></i><b>1.3.14</b> SPSS Data</a></li>
<li class="chapter" data-level="1.3.15" data-path="index.html"><a href="index.html#json"><i class="fa fa-check"></i><b>1.3.15</b> JSON</a></li>
<li class="chapter" data-level="1.3.16" data-path="index.html"><a href="index.html#xml"><i class="fa fa-check"></i><b>1.3.16</b> XML</a></li>
<li class="chapter" data-level="1.3.17" data-path="index.html"><a href="index.html#databases"><i class="fa fa-check"></i><b>1.3.17</b> Databases</a></li>
<li class="chapter" data-level="1.3.18" data-path="index.html"><a href="index.html#apis"><i class="fa fa-check"></i><b>1.3.18</b> APIs</a></li>
<li class="chapter" data-level="1.3.19" data-path="index.html"><a href="index.html#data-manipulation-ideas"><i class="fa fa-check"></i><b>1.3.19</b> Data Manipulation Ideas</a></li>
<li class="chapter" data-level="1.3.20" data-path="index.html"><a href="index.html#documenting-with-markdown"><i class="fa fa-check"></i><b>1.3.20</b> Documenting with Markdown</a></li>
<li class="chapter" data-level="1.3.21" data-path="index.html"><a href="index.html#logical-statements"><i class="fa fa-check"></i><b>1.3.21</b> Logical Statements</a></li>
<li class="chapter" data-level="1.3.22" data-path="index.html"><a href="index.html#dplyr"><i class="fa fa-check"></i><b>1.3.22</b> <code>dplyr</code></a></li>
<li class="chapter" data-level="1.3.23" data-path="index.html"><a href="index.html#reshaping-data"><i class="fa fa-check"></i><b>1.3.23</b> Reshaping Data</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#sas"><i class="fa fa-check"></i><b>1.4</b> SAS</a><ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#basics-of-sas"><i class="fa fa-check"></i><b>1.4.1</b> Basics of SAS</a></li>
<li class="chapter" data-level="1.4.2" data-path="index.html"><a href="index.html#reading-data-with-sas"><i class="fa fa-check"></i><b>1.4.2</b> Reading Data with SAS</a></li>
<li class="chapter" data-level="1.4.3" data-path="index.html"><a href="index.html#manipulating-data-with-sas"><i class="fa fa-check"></i><b>1.4.3</b> Manipulating Data with SAS</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html"><i class="fa fa-check"></i><b>2</b> Sampling Schemes and Experimental Design</a><ul>
<li class="chapter" data-level="2.1" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#data-in-the-wild"><i class="fa fa-check"></i><b>2.1</b> Data in the Wild</a><ul>
<li class="chapter" data-level="2.1.1" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#experimental-study"><i class="fa fa-check"></i><b>2.1.1</b> Experimental Study</a></li>
<li class="chapter" data-level="2.1.2" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#observational-studies"><i class="fa fa-check"></i><b>2.1.2</b> Observational Studies</a></li>
<li class="chapter" data-level="2.1.3" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#observational-vs-experimental-studies"><i class="fa fa-check"></i><b>2.1.3</b> Observational vs Experimental Studies</a></li>
<li class="chapter" data-level="2.1.4" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#the-role-of-statistics"><i class="fa fa-check"></i><b>2.1.4</b> The Role of Statistics</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#motivating-example-sampling---farmers-market"><i class="fa fa-check"></i><b>2.2</b> Motivating Example: Sampling - Farmer’s Market</a><ul>
<li class="chapter" data-level="2.2.1" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#define-objective-background"><i class="fa fa-check"></i><b>2.2.1</b> Define Objective &amp; Background</a></li>
<li class="chapter" data-level="2.2.2" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#select-response"><i class="fa fa-check"></i><b>2.2.2</b> Select Response</a></li>
<li class="chapter" data-level="2.2.3" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#determine-sources-of-variation"><i class="fa fa-check"></i><b>2.2.3</b> Determine Sources of Variation</a></li>
<li class="chapter" data-level="2.2.4" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#select-design"><i class="fa fa-check"></i><b>2.2.4</b> Select Design</a></li>
<li class="chapter" data-level="2.2.5" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#do-study"><i class="fa fa-check"></i><b>2.2.5</b> Do Study</a></li>
<li class="chapter" data-level="2.2.6" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#do-statistical-analysis"><i class="fa fa-check"></i><b>2.2.6</b> Do Statistical Analysis</a></li>
<li class="chapter" data-level="2.2.7" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#draw-conclusions-communicate"><i class="fa fa-check"></i><b>2.2.7</b> Draw Conclusions &amp; Communicate</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#motivating-example-design---student-assessment-volunteers"><i class="fa fa-check"></i><b>2.3</b> Motivating Example: Design - Student Assessment Volunteers</a><ul>
<li class="chapter" data-level="2.3.1" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#define-objective-background-1"><i class="fa fa-check"></i><b>2.3.1</b> Define Objective &amp; Background</a></li>
<li class="chapter" data-level="2.3.2" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#select-response-1"><i class="fa fa-check"></i><b>2.3.2</b> Select Response</a></li>
<li class="chapter" data-level="2.3.3" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#determine-sources-of-variation-1"><i class="fa fa-check"></i><b>2.3.3</b> Determine Sources of Variation</a></li>
<li class="chapter" data-level="2.3.4" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#select-design-1"><i class="fa fa-check"></i><b>2.3.4</b> Select Design</a></li>
<li class="chapter" data-level="2.3.5" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#do-study-1"><i class="fa fa-check"></i><b>2.3.5</b> Do Study</a></li>
<li class="chapter" data-level="2.3.6" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#do-statistical-analysis-1"><i class="fa fa-check"></i><b>2.3.6</b> Do Statistical Analysis</a></li>
<li class="chapter" data-level="2.3.7" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#draw-conclusions-communicate-1"><i class="fa fa-check"></i><b>2.3.7</b> Draw Conclusions &amp; Communicate</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#statistical-ideas-and-concepts"><i class="fa fa-check"></i><b>2.4</b> Statistical Ideas and Concepts</a><ul>
<li class="chapter" data-level="2.4.1" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#sampling-schemes"><i class="fa fa-check"></i><b>2.4.1</b> Sampling Schemes</a></li>
<li class="chapter" data-level="2.4.2" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#fundamentals-of-designed-experiments"><i class="fa fa-check"></i><b>2.4.2</b> Fundamentals of Designed Experiments</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#references-and-readings"><i class="fa fa-check"></i><b>2.5</b> References and Readings</a></li>
<li class="chapter" data-level="2.6" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#software-1"><i class="fa fa-check"></i><b>2.6</b> Software</a><ul>
<li class="chapter" data-level="2.6.1" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#r-1"><i class="fa fa-check"></i><b>2.6.1</b> R</a></li>
<li class="chapter" data-level="2.6.2" data-path="sampling-schemes-and-experimental-design.html"><a href="sampling-schemes-and-experimental-design.html#sas-1"><i class="fa fa-check"></i><b>2.6.2</b> SAS</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="summarizing-data.html"><a href="summarizing-data.html"><i class="fa fa-check"></i><b>3</b> Summarizing Data</a><ul>
<li class="chapter" data-level="3.1" data-path="summarizing-data.html"><a href="summarizing-data.html#motivating-example-summarizing-data---california-health-interview-survey"><i class="fa fa-check"></i><b>3.1</b> Motivating Example: Summarizing Data - California Health Interview Survey</a><ul>
<li class="chapter" data-level="3.1.1" data-path="summarizing-data.html"><a href="summarizing-data.html#define-objective-background-2"><i class="fa fa-check"></i><b>3.1.1</b> Define Objective &amp; Background</a></li>
<li class="chapter" data-level="3.1.2" data-path="summarizing-data.html"><a href="summarizing-data.html#select-response-2"><i class="fa fa-check"></i><b>3.1.2</b> Select Response</a></li>
<li class="chapter" data-level="3.1.3" data-path="summarizing-data.html"><a href="summarizing-data.html#determine-sources-of-variation-2"><i class="fa fa-check"></i><b>3.1.3</b> Determine Sources of Variation</a></li>
<li class="chapter" data-level="3.1.4" data-path="summarizing-data.html"><a href="summarizing-data.html#select-design-2"><i class="fa fa-check"></i><b>3.1.4</b> Select Design</a></li>
<li class="chapter" data-level="3.1.5" data-path="summarizing-data.html"><a href="summarizing-data.html#do-study-2"><i class="fa fa-check"></i><b>3.1.5</b> Do Study</a></li>
<li class="chapter" data-level="3.1.6" data-path="summarizing-data.html"><a href="summarizing-data.html#do-statistical-analysis-2"><i class="fa fa-check"></i><b>3.1.6</b> Do Statistical Analysis</a></li>
<li class="chapter" data-level="3.1.7" data-path="summarizing-data.html"><a href="summarizing-data.html#draw-conclusions-communicate-2"><i class="fa fa-check"></i><b>3.1.7</b> Draw Conclusions &amp; Communicate</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="summarizing-data.html"><a href="summarizing-data.html#statistical-ideas-and-concepts-1"><i class="fa fa-check"></i><b>3.2</b> Statistical Ideas and Concepts</a><ul>
<li class="chapter" data-level="3.2.1" data-path="summarizing-data.html"><a href="summarizing-data.html#scales-types-of-data"><i class="fa fa-check"></i><b>3.2.1</b> Scales (Types) of Data:</a></li>
<li class="chapter" data-level="3.2.2" data-path="summarizing-data.html"><a href="summarizing-data.html#random-variables-and-parameters"><i class="fa fa-check"></i><b>3.2.2</b> Random Variables and Parameters</a></li>
<li class="chapter" data-level="3.2.3" data-path="summarizing-data.html"><a href="summarizing-data.html#numerical-summaries"><i class="fa fa-check"></i><b>3.2.3</b> Numerical Summaries</a></li>
<li class="chapter" data-level="3.2.4" data-path="summarizing-data.html"><a href="summarizing-data.html#graphical-summaries"><i class="fa fa-check"></i><b>3.2.4</b> Graphical Summaries</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="summarizing-data.html"><a href="summarizing-data.html#suggestions-for-further-readings"><i class="fa fa-check"></i><b>3.3</b> Suggestions for Further Readings</a></li>
<li class="chapter" data-level="3.4" data-path="summarizing-data.html"><a href="summarizing-data.html#software-2"><i class="fa fa-check"></i><b>3.4</b> Software</a><ul>
<li class="chapter" data-level="3.4.1" data-path="summarizing-data.html"><a href="summarizing-data.html#r-2"><i class="fa fa-check"></i><b>3.4.1</b> R</a></li>
<li class="chapter" data-level="3.4.2" data-path="summarizing-data.html"><a href="summarizing-data.html#sas-2"><i class="fa fa-check"></i><b>3.4.2</b> SAS</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="point-estimates.html"><a href="point-estimates.html"><i class="fa fa-check"></i><b>4</b> Point Estimates</a><ul>
<li class="chapter" data-level="4.1" data-path="point-estimates.html"><a href="point-estimates.html#estiamte-with-means"><i class="fa fa-check"></i><b>4.1</b> Estiamte with means</a><ul>
<li class="chapter" data-level="4.1.1" data-path="point-estimates.html"><a href="point-estimates.html#experiment-background"><i class="fa fa-check"></i><b>4.1.1</b> Experiment background</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="point-estimates.html"><a href="point-estimates.html#estimate-with-quantiles"><i class="fa fa-check"></i><b>4.2</b> Estimate with quantiles</a><ul>
<li class="chapter" data-level="4.2.1" data-path="point-estimates.html"><a href="point-estimates.html#experiment-background-1"><i class="fa fa-check"></i><b>4.2.1</b> Experiment background</a></li>
<li class="chapter" data-level="4.2.2" data-path="point-estimates.html"><a href="point-estimates.html#define-the-object-of-the-experiment"><i class="fa fa-check"></i><b>4.2.2</b> Define the object of the experiment</a></li>
<li class="chapter" data-level="4.2.3" data-path="point-estimates.html"><a href="point-estimates.html#select-appropriate-response-variables"><i class="fa fa-check"></i><b>4.2.3</b> Select appropriate response variables</a></li>
<li class="chapter" data-level="4.2.4" data-path="point-estimates.html"><a href="point-estimates.html#identify-sources-of-variation"><i class="fa fa-check"></i><b>4.2.4</b> IDentify sources of variation</a></li>
<li class="chapter" data-level="4.2.5" data-path="point-estimates.html"><a href="point-estimates.html#choose-an-experimental-design"><i class="fa fa-check"></i><b>4.2.5</b> Choose an experimental design</a></li>
<li class="chapter" data-level="4.2.6" data-path="point-estimates.html"><a href="point-estimates.html#perform-the-test"><i class="fa fa-check"></i><b>4.2.6</b> Perform the test</a></li>
<li class="chapter" data-level="4.2.7" data-path="point-estimates.html"><a href="point-estimates.html#statistically-analyze-the-data"><i class="fa fa-check"></i><b>4.2.7</b> Statistically analyze the data</a></li>
<li class="chapter" data-level="4.2.8" data-path="point-estimates.html"><a href="point-estimates.html#draw-conclusions"><i class="fa fa-check"></i><b>4.2.8</b> Draw conclusions</a></li>
<li class="chapter" data-level="4.2.9" data-path="point-estimates.html"><a href="point-estimates.html#discussion"><i class="fa fa-check"></i><b>4.2.9</b> Discussion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="accounting-for-uncertainty.html"><a href="accounting-for-uncertainty.html"><i class="fa fa-check"></i><b>5</b> Accounting for Uncertainty</a><ul>
<li class="chapter" data-level="5.1" data-path="accounting-for-uncertainty.html"><a href="accounting-for-uncertainty.html#example-one"><i class="fa fa-check"></i><b>5.1</b> Example one</a></li>
<li class="chapter" data-level="5.2" data-path="accounting-for-uncertainty.html"><a href="accounting-for-uncertainty.html#example-two"><i class="fa fa-check"></i><b>5.2</b> Example two</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="CI.html"><a href="CI.html"><i class="fa fa-check"></i><b>6</b> Inference via Confidence Intervals for One Sample</a><ul>
<li class="chapter" data-level="6.1" data-path="CI.html"><a href="CI.html#the-normal-approximation"><i class="fa fa-check"></i><b>6.1</b> The normal approximation</a><ul>
<li class="chapter" data-level="6.1.1" data-path="CI.html"><a href="CI.html#analog-ci"><i class="fa fa-check"></i><b>6.1.1</b> Analog CI</a></li>
<li class="chapter" data-level="6.1.2" data-path="CI.html"><a href="CI.html#easy-mode"><i class="fa fa-check"></i><b>6.1.2</b> Easy mode</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="CI.html"><a href="CI.html#other-types-of-binomial-confidence-intervals"><i class="fa fa-check"></i><b>6.2</b> Other types of binomial confidence intervals</a><ul>
<li class="chapter" data-level="6.2.1" data-path="CI.html"><a href="CI.html#exact-cis-aka-clopper-pearson"><i class="fa fa-check"></i><b>6.2.1</b> Exact CIs, aka Clopper-Pearson</a></li>
<li class="chapter" data-level="6.2.2" data-path="CI.html"><a href="CI.html#bayesian-intervals"><i class="fa fa-check"></i><b>6.2.2</b> Bayesian intervals</a></li>
<li class="chapter" data-level="6.2.3" data-path="CI.html"><a href="CI.html#a-good-general-use-ci"><i class="fa fa-check"></i><b>6.2.3</b> A good general-use CI</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="HT.html"><a href="HT.html"><i class="fa fa-check"></i><b>7</b> Inference via Hypothesis Tests for One Sample</a><ul>
<li class="chapter" data-level="7.1" data-path="HT.html"><a href="HT.html#example-detection-probability"><i class="fa fa-check"></i><b>7.1</b> Example: Detection Probability</a><ul>
<li class="chapter" data-level="7.1.1" data-path="HT.html"><a href="HT.html#understanding-system-performance"><i class="fa fa-check"></i><b>7.1.1</b> Understanding system performance</a></li>
<li class="chapter" data-level="7.1.2" data-path="HT.html"><a href="HT.html#data-analysis"><i class="fa fa-check"></i><b>7.1.2</b> Data Analysis</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="HT.html"><a href="HT.html#hypothesis-testing"><i class="fa fa-check"></i><b>7.2</b> Hypothesis testing</a><ul>
<li class="chapter" data-level="7.2.1" data-path="HT.html"><a href="HT.html#wald-tests"><i class="fa fa-check"></i><b>7.2.1</b> Wald tests</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="twocategorical.html"><a href="twocategorical.html"><i class="fa fa-check"></i><b>8</b> Inference for Two Categorical Variables</a></li>
<li class="chapter" data-level="9" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>9</b> One-Way ANOVA</a><ul>
<li class="chapter" data-level="9.1" data-path="anova.html"><a href="anova.html#motivating-example"><i class="fa fa-check"></i><b>9.1</b> Motivating example</a></li>
<li class="chapter" data-level="9.2" data-path="anova.html"><a href="anova.html#simple-model-for-the-data"><i class="fa fa-check"></i><b>9.2</b> Simple model for the data</a></li>
<li class="chapter" data-level="9.3" data-path="anova.html"><a href="anova.html#exploratory-analysis"><i class="fa fa-check"></i><b>9.3</b> exploratory analysis</a></li>
<li class="chapter" data-level="9.4" data-path="anova.html"><a href="anova.html#sources-of-variation-1"><i class="fa fa-check"></i><b>9.4</b> sources of variation</a></li>
<li class="chapter" data-level="9.5" data-path="anova.html"><a href="anova.html#statistical-model-and-analysis"><i class="fa fa-check"></i><b>9.5</b> statistical model and analysis</a></li>
<li class="chapter" data-level="9.6" data-path="anova.html"><a href="anova.html#compare-analyses"><i class="fa fa-check"></i><b>9.6</b> compare analyses</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="multiway.html"><a href="multiway.html"><i class="fa fa-check"></i><b>10</b> Multi-way ANOVA</a></li>
<li class="chapter" data-level="11" data-path="block.html"><a href="block.html"><i class="fa fa-check"></i><b>11</b> Block Designs</a></li>
<li class="chapter" data-level="12" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>12</b> Regression Models</a></li>
<li class="chapter" data-level="13" data-path="glm.html"><a href="glm.html"><i class="fa fa-check"></i><b>13</b> The General Linear Model</a></li>
<li class="chapter" data-level="14" data-path="mixedmodels.html"><a href="mixedmodels.html"><i class="fa fa-check"></i><b>14</b> Mixed Models</a></li>
<li class="chapter" data-level="15" data-path="repeatedmeasures.html"><a href="repeatedmeasures.html"><i class="fa fa-check"></i><b>15</b> Split Plot and Repeated Measures Designs</a></li>
<li class="chapter" data-level="16" data-path="logistic.html"><a href="logistic.html"><i class="fa fa-check"></i><b>16</b> Logistic Regression and Generalized Linear Models</a><ul>
<li class="chapter" data-level="16.1" data-path="logistic.html"><a href="logistic.html#stuff-here"><i class="fa fa-check"></i><b>16.1</b> Stuff here</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="glmm.html"><a href="glmm.html"><i class="fa fa-check"></i><b>17</b> Generalized Linear Mixed Models</a></li>
<li class="chapter" data-level="18" data-path="learningobj.html"><a href="learningobj.html"><i class="fa fa-check"></i><b>18</b> Appendix - Learning Objectives</a><ul>
<li class="chapter" data-level="18.1" data-path="learningobj.html"><a href="learningobj.html#book-level"><i class="fa fa-check"></i><b>18.1</b> Book-level</a></li>
<li class="chapter" data-level="18.2" data-path="learningobj.html"><a href="learningobj.html#topic-level"><i class="fa fa-check"></i><b>18.2</b> Topic-level</a><ul>
<li class="chapter" data-level="18.2.1" data-path="learningobj.html"><a href="learningobj.html#chapter-2---sampling-design-and-exploratory-data-analysis"><i class="fa fa-check"></i><b>18.2.1</b> Chapter 2 - Sampling, Design, and Exploratory Data Analysis</a></li>
<li class="chapter" data-level="18.2.2" data-path="learningobj.html"><a href="learningobj.html#chapter-3---point-estimation"><i class="fa fa-check"></i><b>18.2.2</b> Chapter 3 - Point Estimation</a></li>
<li class="chapter" data-level="18.2.3" data-path="learningobj.html"><a href="learningobj.html#chapter-4---accounting-for-uncertainty-in-estimation"><i class="fa fa-check"></i><b>18.2.3</b> Chapter 4 - Accounting for Uncertainty in Estimation</a></li>
<li class="chapter" data-level="18.2.4" data-path="learningobj.html"><a href="learningobj.html#chapter-5---inference-via-hypothesis-testing-for-a-proportion-or-mean"><i class="fa fa-check"></i><b>18.2.4</b> Chapter 5 - Inference via Hypothesis Testing for a Proportion or Mean</a></li>
<li class="chapter" data-level="18.2.5" data-path="learningobj.html"><a href="learningobj.html#chapter-6---inference-via-confidence-intervals-for-a-proportion-or-mean"><i class="fa fa-check"></i><b>18.2.5</b> Chapter 6 - Inference via Confidence Intervals for a Proportion or Mean</a></li>
<li class="chapter" data-level="18.2.6" data-path="learningobj.html"><a href="learningobj.html#chapter-7---inference-on-two-categorical-variables"><i class="fa fa-check"></i><b>18.2.6</b> Chapter 7 - Inference on Two Categorical Variables</a></li>
<li class="chapter" data-level="18.2.7" data-path="learningobj.html"><a href="learningobj.html#chapter-8---inference-for-multiple-means"><i class="fa fa-check"></i><b>18.2.7</b> Chapter 8 - Inference for Multiple Means</a></li>
<li class="chapter" data-level="18.2.8" data-path="learningobj.html"><a href="learningobj.html#chapter-9---multiway-anova"><i class="fa fa-check"></i><b>18.2.8</b> Chapter 9 - Multiway ANOVA</a></li>
<li class="chapter" data-level="18.2.9" data-path="learningobj.html"><a href="learningobj.html#chapter-10---block-designs"><i class="fa fa-check"></i><b>18.2.9</b> Chapter 10 - Block Designs</a></li>
<li class="chapter" data-level="18.2.10" data-path="learningobj.html"><a href="learningobj.html#chapter-11---regression"><i class="fa fa-check"></i><b>18.2.10</b> Chapter 11 - Regression</a></li>
<li class="chapter" data-level="18.2.11" data-path="learningobj.html"><a href="learningobj.html#chapter-12---the-general-linear-model"><i class="fa fa-check"></i><b>18.2.11</b> Chapter 12 - The General Linear Model</a></li>
<li class="chapter" data-level="18.2.12" data-path="learningobj.html"><a href="learningobj.html#chapter-13---mixed-models"><i class="fa fa-check"></i><b>18.2.12</b> Chapter 13 - Mixed Models</a></li>
<li class="chapter" data-level="18.2.13" data-path="learningobj.html"><a href="learningobj.html#chapter-14---repeated-measures-and-split-plot-designs"><i class="fa fa-check"></i><b>18.2.13</b> Chapter 14 - Repeated Measures and Split Plot Designs</a></li>
<li class="chapter" data-level="18.2.14" data-path="learningobj.html"><a href="learningobj.html#chapter-15---logistic-regression-and-generalized-linear-models"><i class="fa fa-check"></i><b>18.2.14</b> Chapter 15 - Logistic Regression and Generalized Linear Models</a></li>
<li class="chapter" data-level="18.2.15" data-path="learningobj.html"><a href="learningobj.html#chapter-16---generalized-linear-mixed-models"><i class="fa fa-check"></i><b>18.2.15</b> Chapter 16 - Generalized Linear Mixed Models</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="learningobj.html"><a href="learningobj.html#from-st512"><i class="fa fa-check"></i><b>18.3</b> From ST512</a></li>
<li class="chapter" data-level="18.4" data-path="learningobj.html"><a href="learningobj.html#for-point-estimates-chapter"><i class="fa fa-check"></i><b>18.4</b> For Point Estimates Chapter</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="19" data-path="notation.html"><a href="notation.html"><i class="fa fa-check"></i><b>19</b> Appendix - Notation</a><ul>
<li class="chapter" data-level="19.1" data-path="notation.html"><a href="notation.html#standard-notation"><i class="fa fa-check"></i><b>19.1</b> Standard notation</a></li>
<li class="chapter" data-level="19.2" data-path="notation.html"><a href="notation.html#mixed-models"><i class="fa fa-check"></i><b>19.2</b> Mixed models</a></li>
<li class="chapter" data-level="19.3" data-path="notation.html"><a href="notation.html#effects-model-representation"><i class="fa fa-check"></i><b>19.3</b> Effects model representation</a></li>
<li class="chapter" data-level="19.4" data-path="notation.html"><a href="notation.html#estimators-vs.-estimates"><i class="fa fa-check"></i><b>19.4</b> Estimators vs. Estimates</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Methods</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="summarizing-data" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Summarizing Data</h1>
<p>Recall a major goal of conducting a study is often to conduct statistical inference. Inference can involve determining which variables are important in relation to a response variable and/or predicting a response variable under different scenarios. To formally do inference we need to define the population of interest as well as <strong>parameters</strong> we want to study.</p>
<ul>
<li><p>Population - all the values, items, or individuals of interest</p></li>
<li><p>Parameter - a summary measure about a population</p></li>
</ul>
<p>Ideally, we’d be able to measure every member of the population and exactly calculate the value of any population parameter. This would involved conducing a census. A census is usually not feasible. Instead we take a subset of the population and try to use these observations to make statements or claims about the population.</p>
<ul>
<li><p>Sample - a subset of the population we observe data on</p></li>
<li><p>Statistic - a summary value calculated from the sample observations</p></li>
</ul>
<p>(<strong>A good visual of inference here</strong>)</p>
<p>Your questions of interest will often lead you to which parameters you have interest in. Careful consideration of study goals and the time and money you have will also most likely lead you to which type of data you will collect to best make inference on those parameters. Other times, you must work with existing data that has already been collected. When this is the case, the data will sometimes guide the parameters you can investigate and ultimately the claims you can make.</p>
<div id="motivating-example-summarizing-data---california-health-interview-survey" class="section level2">
<h2><span class="header-section-number">3.1</span> Motivating Example: Summarizing Data - California Health Interview Survey</h2>
<div id="define-objective-background-2" class="section level3">
<h3><span class="header-section-number">3.1.1</span> Define Objective &amp; Background</h3>
<p><img src="img/defineObjective.png" width="13%" style="float:left; padding:10px" />
Look at the California Health Interview Survey (CHIS). Describe the idea of the survey. For our purpose we’ll imagine the dataset itself is the population of interest. We will take a sample from that population to investigate and summarize as well as compare to the truth.</p>
<p> </p>
<p> </p>
<p> </p>
<p> </p>
</div>
<div id="select-response-2" class="section level3">
<h3><span class="header-section-number">3.1.2</span> Select Response</h3>
<p><img src="img/selectResponse.png" width="13%" style="float:left; padding:10px" />
Response is really certain variables in the dataset, maybe BMI or some other health related statistic we want to study.</p>
<p> </p>
<p> </p>
<p> </p>
<p> </p>
</div>
<div id="determine-sources-of-variation-2" class="section level3">
<h3><span class="header-section-number">3.1.3</span> Determine Sources of Variation</h3>
<p><img src="img/determineVariation.png" width="13%" style="float:left; padding:10px" />
Sources of variation include height, weight, ethnicity, etc. Going to take those into account.</p>
<p> </p>
<p> </p>
<p> </p>
<p> </p>
</div>
<div id="select-design-2" class="section level3">
<h3><span class="header-section-number">3.1.4</span> Select Design</h3>
<p><img src="img/selectDesign.png" width="13%" style="float:left; padding:10px" />
Design will be to do a SRS and do an observational study - basically an exploration study. (Maybe also do an Stratified one and compare the results? Maybe that should be left as an exercise.)</p>
<p> </p>
<p> </p>
<p> </p>
<p> </p>
</div>
<div id="do-study-2" class="section level3">
<h3><span class="header-section-number">3.1.5</span> Do Study</h3>
<p><img src="img/conductStudy.png" width="13%" style="float:left; padding:10px" />
Pretend that we got 100% response rate and all that good stuff. Maybe discuss the idea of missingness here but probably not the right time.</p>
<p> </p>
<p> </p>
<p> </p>
<p> </p>
</div>
<div id="do-statistical-analysis-2" class="section level3">
<h3><span class="header-section-number">3.1.6</span> Do Statistical Analysis</h3>
<p><img src="img/statsAnalysis.png" width="13%" style="float:left; padding:10px" />
Main analysis is just to summarize the data set. As an exercise we will compare the sample to the population since we actually know it here.</p>
<p> </p>
<p> </p>
<p> </p>
<p> </p>
</div>
<div id="draw-conclusions-communicate-2" class="section level3">
<h3><span class="header-section-number">3.1.7</span> Draw Conclusions &amp; Communicate</h3>
<p><img src="img/concludeCommunicate.png" width="13%" style="float:left; padding:10px" />
Describe main results or takeaways to study in the future. How to present some graphs as well (i.e. don’t just put a graph, it must be described and meaningful or don’t report it). Appropriate use of titles and labels too.</p>
<p> </p>
<p> </p>
<p> </p>
<p> </p>
</div>
</div>
<div id="statistical-ideas-and-concepts-1" class="section level2">
<h2><span class="header-section-number">3.2</span> Statistical Ideas and Concepts</h2>
<p>We’ve seen the importance of obtaining sample units in a valid way and, when applicable, using a sound experimental design. We also need to have a strong understanding of the types of data or variables we might collect. The type of data collected is inherently linked to the types of conclusions that can be drawn.</p>
<div id="scales-types-of-data" class="section level3">
<h3><span class="header-section-number">3.2.1</span> Scales (Types) of Data:</h3>
<p>Consider a dataset where the rows represent observations and the columns represent variables. These variables can generally be of two main types:</p>
<ul>
<li><p><strong>Quantitative or Numerical variable</strong> - A variable that is described by numerical measurements where arithmetic can be performed.</p></li>
<li><p><strong>Qualitative or Categorical variable</strong> - A variable that is described by attributes or labels.</p></li>
</ul>
<p>We’ll generally refer to these as numerical and categorical, respectively. Numerical variables can be further refined into two subscales:</p>
<ul>
<li><p>Discrete - finite or countably infinite number of values (# of cars passing through an intersection in an hour, 0, 1, 2, …)</p></li>
<li><p>Continuous - any value in an interval is possible (Temperature, <span class="math inline">\((-459.67\deg F, \infty)\)</span></p></li>
</ul>
<p>Categorical variables can be refined into two subscales as well:</p>
<ul>
<li><p>Nominal - categories have no ordering (Male, Female) (zip codes)</p></li>
<li><p>Ordinal - can order categories (Lickert scale data) (college football rankings)</p></li>
</ul>
<p>How we summarize and analyze the data will depend on which type of data we have! Fully understanding the different types of data and how they can be linked to parameters of interest is vital importance when it comes to setting your study’s goals. The two examples below give some parameters commonly looked at when conducting inference.</p>
<p><strong>Two examples here, linking to parameters - one with mean and quantile of interest? one with proportion and odds</strong></p>
</div>
<div id="random-variables-and-parameters" class="section level3">
<h3><span class="header-section-number">3.2.2</span> Random Variables and Parameters</h3>
<p>Intro RVs and changing all variables measured to take on quantitative values. Binomial idea, multinomial for 3+ categories.</p>
<p>Population variables have a population distribution or pattern and frequency. These are equivalently described by probability histograms, tables, or probability mass functions (PMFs) for discrete random variables. Continuous modeled by a density or probability density function (PDF). Understanding distributions is important because they allow us to find probabilities, know the average value, etc. We’ll take up population distributions in the next chapters. For now we’ll focus on describing data and sample distributions. Why?</p>
</div>
<div id="numerical-summaries" class="section level3">
<h3><span class="header-section-number">3.2.3</span> Numerical Summaries</h3>
<p>In this chapter we’ll discuss summarizing data only, not populations. We’ll calculate numerical summaries (statistics) and graphical summaries for the sample. In the next chapter we’ll relate these summaries to the population parameters and distributions.</p>
<p>The focus of this section is to talk about what summaries you’d want to create and why, along with how to interpret them. The software section discusses the creation of the summaries in R and SAS.</p>
<p>What do we want to describe? The goal of descriptive statistics is to describe the <strong>distribution</strong> of the data. That is, how the data was observed. We often want to summarize measures of location and measures of spread for the data. Combining these summaries (along with graphs) gives us a solid understanding of the variable’s distribution.</p>
<p>Note: The things we want to describe about the sample are similar to things we want to describe about the population. Again, we’ll discuss this relation in more detail in future chapters.</p>
<ul>
<li><p>Measures of Location</p>
<ul>
<li>Sample Mean = <span class="math inline">\(\bar{Y}=\frac{\sum_{i=1}^{n}Y_i}{n}\)</span></li>
<li>Sample Median = Middle value of the data set (50% of values to left, 50% of values to right)</li>
<li>Sample Proportion = <span class="math inline">\(\hat{p}=\frac{\#\mbox{ of successes}}{\mbox{sample size}}\)</span></li>
<li>Sample Quantiles or Sample Percentiles</li>
</ul></li>
<li><p>Measures of Spread</p>
<ul>
<li>Sample Variance = <span class="math inline">\(S^2 = \frac{\sum_{i=1}^{n}(Y_i-\bar{Y})^2}{n-1}\)</span></li>
<li>Sample Standard Deviation = <span class="math inline">\(S\)</span></li>
<li>Sample Range = <span class="math inline">\(max(Y_1,...,Y_n)-min(Y_1,...,Y_n)\)</span></li>
<li>Inter-quartile Range = Q3-Q1</li>
</ul></li>
</ul>
<p>When summarizing data we want to describe the distribution of the data. This may be a <em>marginal</em> or <em>univariate</em> summary of a single variable by itself.</p>
<p><img src="img/summarizeAllF.png" width="40%" style="display: block; margin: auto;" /></p>
<p>However, quite often we want to look at the distribution of a variable conditional on another variable - perhaps levels of a certain factor or the treatments of an experiment - or the relationship of more than one variable together. These would be referred to as <strong>multivariate</strong> summaries.</p>
<p><img src="img/summarizeGroupsF.png" width="50%" style="display: block; margin: auto;" /></p>
<p>How we summarize data depends on the <strong>variable types</strong> (sometimes called <strong>variable scales</strong>) and the attribute or quantity we are trying to describe about that variable. The two major types of variables are:</p>
<ul>
<li>Categorical (Qualitative) variable - entries are a label or attribute<br />
</li>
<li>Numerical (Quantitative) variable - entries are a numerical value where math can be performed</li>
</ul>
<p><img src="img/variableTypes.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Both of these have <em>subscales</em> that are sometimes important to consider.</p>
<p>Categorical variables can be <strong>nominal</strong> or <strong>ordinal</strong>. Nominal variables have no ordering to their categories. For example, a variable asking for your favorite pet. There is no inherent ordering to give pets. Ordinal variables have an ordering but differences between the categories are not necessarily the same. For example, Likert scale data having categories “strongly disagree,” “disagree,” “neutral,” “agree”, and “strongly agree.” There is a clear ordering here but the difference between strongly agree and agree is not necessarily the same as the difference between agree and neutral.</p>
<p>Numerical variables can be <strong>discrete</strong> or <strong>continuous</strong>. Discrete variables take on values that can be listed out, although the list may continue on indefinitely. For example, the number of bedrooms in a house. The values (or support) for this variable are 0, 1, 2, 3, … but there is not necessarily a known upper limit. Discrete variables don’t need to take on just integers and make take on values that are irregularly spaced. A continuous variable is one in which the variable can take on any value in an interval (or union of intervals). For example, the time it takes to complete an online survey. The support for this variable would be the interval from 0 to some large number, often we’d just say infinity for the upper bound.</p>
<p>When summarizing the variables, the main goal is to summarize the <strong>distribution</strong> or pattern and frequency with which you observe a variable. This involves slightly different summaries dependong on variable type (or combination of variable types).</p>
<ul>
<li><p>Categorical variable - describe relative frequency (or count) in each category</p></li>
<li><p>Numerical variable - describe the shape, center, and spread of the distribution</p></li>
</ul>
<p>The most common numerical summaries are given below:</p>
<ul>
<li><p>Cateogrical</p>
<ul>
<li>Contingency Tables</li>
</ul></li>
<li><p>Numerical</p>
<ul>
<li>Mean/Median<br />
</li>
<li>Standard Deviation/Variance</li>
<li>Coefficient of Variation</li>
<li>Quantiles/Percentiles/IQR</li>
</ul></li>
</ul>
<p>These are certainly not the only summaries you might calculate!</p>
<p><strong>This is terribe but I want to put something like it somewhere…</strong> If you have two or more categorical variables, contingency tables are still the summary to use. If you have one numerical and one or more categorical variable, you’ll often calculate the numerical summaries for each combination of categorical variables levels. If you have multiple numerical variables you’ll usually calculate the covariance or correlation, which measures the linear relationship between pairs of variables. This can also be done for different settings of categorical variables as well.</p>
<p>Next, we’ll go through the details of how these summaries are calculated and how to interpret them.</p>
<div id="contingency-tables-for-categorical-variables" class="section level4">
<h4><span class="header-section-number">3.2.3.1</span> Contingency Tables for Categorical Variables</h4>
<p>Let’s start by summarizing a categorical variable (entries are a label or attribute) from a dataset on the titanic passengers. The dataset describes attributes of passengers on the titanic. The variables we’ll investigate are</p>
<ul>
<li>embarked (where journey started)<br />
</li>
<li>survived (survive or not)<br />
</li>
<li>sex (Male or Female)</li>
</ul>
<p>A few observations from the data are given below.</p>
<table>
<thead>
<tr class="header">
<th align="left">name</th>
<th align="right">survived</th>
<th align="left">sex</th>
<th align="left">embarked</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Allen, Miss. Elisabeth Walton</td>
<td align="right">1</td>
<td align="left">female</td>
<td align="left">S</td>
</tr>
<tr class="even">
<td align="left">Allison, Master. Hudson Trevor</td>
<td align="right">1</td>
<td align="left">male</td>
<td align="left">S</td>
</tr>
<tr class="odd">
<td align="left">Allison, Miss. Helen Loraine</td>
<td align="right">0</td>
<td align="left">female</td>
<td align="left">S</td>
</tr>
<tr class="even">
<td align="left">Allison, Mr. Hudson Joshua Creighton</td>
<td align="right">0</td>
<td align="left">male</td>
<td align="left">S</td>
</tr>
<tr class="odd">
<td align="left">Allison, Mrs. Hudson J C (Bessie Waldo Daniels)</td>
<td align="right">0</td>
<td align="left">female</td>
<td align="left">S</td>
</tr>
<tr class="even">
<td align="left">Anderson, Mr. Harry</td>
<td align="right">1</td>
<td align="left">male</td>
<td align="left">S</td>
</tr>
<tr class="odd">
<td align="left">Andrews, Miss. Kornelia Theodosia</td>
<td align="right">1</td>
<td align="left">female</td>
<td align="left">S</td>
</tr>
<tr class="even">
<td align="left">Andrews, Mr. Thomas Jr</td>
<td align="right">0</td>
<td align="left">male</td>
<td align="left">S</td>
</tr>
<tr class="odd">
<td align="left">Appleton, Mrs. Edward Dale (Charlotte Lamson)</td>
<td align="right">1</td>
<td align="left">female</td>
<td align="left">S</td>
</tr>
<tr class="even">
<td align="left">Artagaveytia, Mr. Ramon</td>
<td align="right">0</td>
<td align="left">male</td>
<td align="left">C</td>
</tr>
</tbody>
</table>
<p>A contingency table simply shows the frequency or count (sometimes proportion) of observations falling into the categories of the variable. If we are looking at one variable by itself, the table is called a <strong>one-way contingency tables</strong>.</p>
<p>A one-way contingency table for the <code>embarked</code> variable:</p>
<table>
<thead>
<tr class="header">
<th align="left">Port</th>
<th align="right">Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Cherbourg</td>
<td align="right">270</td>
</tr>
<tr class="even">
<td align="left">Queenstown</td>
<td align="right">123</td>
</tr>
<tr class="odd">
<td align="left">Southampton</td>
<td align="right">914</td>
</tr>
</tbody>
</table>
<p>A one-way contingency table for the <code>survived</code> variable:</p>
<table>
<thead>
<tr class="header">
<th align="left">Status</th>
<th align="right">Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Died</td>
<td align="right">809</td>
</tr>
<tr class="even">
<td align="left">Survived</td>
<td align="right">500</td>
</tr>
</tbody>
</table>
<p>A one-way contingency table for the <code>sex</code> variable:</p>
<table>
<thead>
<tr class="header">
<th align="left">Sex</th>
<th align="right">Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Female</td>
<td align="right">466</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="right">843</td>
</tr>
</tbody>
</table>
<p>We can see that these one-way tables allow us to easily see how many values fall in each category for a given variable. For example, there were 270 people that embarked at the Cherbourg port. We can also see that 809 people died and 500 survived.</p>
<p>A <strong>two-way contingency table</strong> is similar in that it gives the frequencies for combinations of two categorical variables.</p>
<p>A two-way contingency table between the <code>survived</code> and <code>sex</code> variables:</p>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">Female</th>
<th align="right">Male</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Died</td>
<td align="right">127</td>
<td align="right">682</td>
</tr>
<tr class="even">
<td>Survived</td>
<td align="right">339</td>
<td align="right">161</td>
</tr>
</tbody>
</table>
<p>A two-way contingency table between the <code>survived</code> and <code>embarked</code> variables:</p>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">Cherbourg</th>
<th align="right">Queenstown</th>
<th align="right">Southampton</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Died</td>
<td align="right">120</td>
<td align="right">79</td>
<td align="right">610</td>
</tr>
<tr class="even">
<td>Survived</td>
<td align="right">150</td>
<td align="right">44</td>
<td align="right">304</td>
</tr>
</tbody>
</table>
<p>A two-way contingency table between the <code>sex</code> and <code>embarked</code> variables:</p>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">Cherbourg</th>
<th align="right">Queenstown</th>
<th align="right">Southampton</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Female</td>
<td align="right">113</td>
<td align="right">60</td>
<td align="right">291</td>
</tr>
<tr class="even">
<td>Male</td>
<td align="right">157</td>
<td align="right">63</td>
<td align="right">623</td>
</tr>
</tbody>
</table>
<p>With this summary we can easily see the relationship between these <strong>pairs</strong> of categorical variables. For example, there were 127 females that died and 682 males that died.</p>
<p>This idea can be extended to included combinations of as many categorical variables as desired. Generally these are called <strong>n-way contingency tables</strong>. The major issue with going beyond two- or three-way tables is the difficulty in displaying the information in a easy to digest manner. Consider the three-way table between <code>sex</code>, <code>embarked</code>, and <code>survived</code> created below.</p>
<table>
<thead>
<tr class="header">
<th align="left">Sex</th>
<th align="left">Port</th>
<th align="left">Status</th>
<th align="right">Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Female</td>
<td align="left">Cherbourg</td>
<td align="left">Died</td>
<td align="right">11</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">Cherbourg</td>
<td align="left">Died</td>
<td align="right">109</td>
</tr>
<tr class="odd">
<td align="left">Female</td>
<td align="left">Queenstown</td>
<td align="left">Died</td>
<td align="right">23</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">Queenstown</td>
<td align="left">Died</td>
<td align="right">56</td>
</tr>
<tr class="odd">
<td align="left">Female</td>
<td align="left">Southampton</td>
<td align="left">Died</td>
<td align="right">93</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">Southampton</td>
<td align="left">Died</td>
<td align="right">517</td>
</tr>
<tr class="odd">
<td align="left">Female</td>
<td align="left">Cherbourg</td>
<td align="left">Survived</td>
<td align="right">102</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">Cherbourg</td>
<td align="left">Survived</td>
<td align="right">48</td>
</tr>
<tr class="odd">
<td align="left">Female</td>
<td align="left">Queenstown</td>
<td align="left">Survived</td>
<td align="right">37</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">Queenstown</td>
<td align="left">Survived</td>
<td align="right">7</td>
</tr>
<tr class="odd">
<td align="left">Female</td>
<td align="left">Southampton</td>
<td align="left">Survived</td>
<td align="right">198</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">Southampton</td>
<td align="left">Survived</td>
<td align="right">106</td>
</tr>
</tbody>
</table>
<p>This isn’t quite as easy to digest as before but still quite useful. The first row shows that there were 11 females that embarked at the Cerbourg port that died.</p>
<p>Sometimes it is useful to look at a one-way table conditional on settings of other variables as well. For instance, we could report a one-way table for the <code>survived</code> variable conditional on looking at males that embarked at Queenstown.</p>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Died</td>
<td align="right">56</td>
</tr>
<tr class="even">
<td>Survived</td>
<td align="right">7</td>
</tr>
</tbody>
</table>
<p>We see that, of males that embarked at the Queenstown port, 56 died and 7 survived.</p>
<p>Again, contingency tables or n-way tables are the most common summary for combinations of categorical variables. They are important because they allow us to summarize how often categories, or combinations of categories, were observed in a dataset.</p>
<p><strong>Not sure if I want to include all of this below…, especially for this data set since the population is the sample… Also I should talk about that above probably…</strong></p>
<p>We might also want to know the relative frequency or sample proportion of obsrervations falling into each category (or combination of categories). This can be done by dividing each entry by the sample size, <span class="math inline">\(n\)</span> (the total number of observations).</p>
<p>Generically, we might say the categories have a probability or proportion associated with them for the population. For the embarked variable we’d have…
Probabilities interpreted as the long-run relative frequency of occurrence. Maybe discuss indicator variables for the two with character strings for labels…</p>
</div>
<div id="measures-of-location-and-spread-for-numerical-variables" class="section level4">
<h4><span class="header-section-number">3.2.3.2</span> Measures of Location and Spread for Numerical Variables</h4>
<p>Recall that a numerical variable is one whose entries are a numerical value where math can be performed. The major things we want to describe about a numerical variable’s distribution are the shape, center, and spread. Shape is best left to graphical summaries like a histogram or density plot. We’ll cover these shortly.</p>
<p>Let’s consider a dataset about an experiment on carbon dioxide (CO2) uptake in grass. The three variables we’ll investigate are:</p>
<ul>
<li>Response recorded: <code>uptake</code> CO2 uptake rates in grass plants (labeled with <span class="math inline">\(y\)</span>)<br />
</li>
<li>Environment manipulated: <code>Treatment</code> - chilled/nonchilled (labeled with <span class="math inline">\(x_1\)</span>)<br />
</li>
<li>Ambient CO2 specified and measured: <code>conc</code> (labeled with <span class="math inline">\(x_2\)</span>)</li>
</ul>
<p><code>uptake</code> is a numerical variable and will be the variable we want to summarize. <code>Treatment</code> is a categorical variable. <code>conc</code> is a numerical variable but only observed at a few values. This can be treated as either type of variable depending on what your goal is. We will treat <code>conc</code> as numerical. A snippet of the full dataset appears below.</p>
<table>
<thead>
<tr class="header">
<th align="left">Plant</th>
<th align="left">Type</th>
<th align="left">Treatment</th>
<th align="right">conc</th>
<th align="right">uptake</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Qn1</td>
<td align="left">Quebec</td>
<td align="left">nonchilled</td>
<td align="right">95</td>
<td align="right">16.0</td>
</tr>
<tr class="even">
<td align="left">Qn1</td>
<td align="left">Quebec</td>
<td align="left">nonchilled</td>
<td align="right">175</td>
<td align="right">30.4</td>
</tr>
<tr class="odd">
<td align="left">Qn1</td>
<td align="left">Quebec</td>
<td align="left">nonchilled</td>
<td align="right">250</td>
<td align="right">34.8</td>
</tr>
<tr class="even">
<td align="left">Qn1</td>
<td align="left">Quebec</td>
<td align="left">nonchilled</td>
<td align="right">350</td>
<td align="right">37.2</td>
</tr>
<tr class="odd">
<td align="left">Qn1</td>
<td align="left">Quebec</td>
<td align="left">nonchilled</td>
<td align="right">500</td>
<td align="right">35.3</td>
</tr>
<tr class="even">
<td align="left">Qn1</td>
<td align="left">Quebec</td>
<td align="left">nonchilled</td>
<td align="right">675</td>
<td align="right">39.2</td>
</tr>
<tr class="odd">
<td align="left">Qn1</td>
<td align="left">Quebec</td>
<td align="left">nonchilled</td>
<td align="right">1000</td>
<td align="right">39.7</td>
</tr>
<tr class="even">
<td align="left">Qn2</td>
<td align="left">Quebec</td>
<td align="left">nonchilled</td>
<td align="right">95</td>
<td align="right">13.6</td>
</tr>
<tr class="odd">
<td align="left">Qn2</td>
<td align="left">Quebec</td>
<td align="left">nonchilled</td>
<td align="right">175</td>
<td align="right">27.3</td>
</tr>
<tr class="even">
<td align="left">Qn2</td>
<td align="left">Quebec</td>
<td align="left">nonchilled</td>
<td align="right">250</td>
<td align="right">37.1</td>
</tr>
</tbody>
</table>
<p>In the next section we’ll discuss formulae for calculating some of the summaries. It is important to understand the labeling of the data in order to help decipher those formulae.</p>
<table>
<thead>
<tr class="header">
<th><code>uptake</code> (<span class="math inline">\(y\)</span>)</th>
<th><code>conc</code> (<span class="math inline">\(x_1\)</span>)</th>
<th><code>Treatment</code> (<span class="math inline">\(x_2\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(y_1 =\)</span> 16</td>
<td><span class="math inline">\(x_{1,1} =\)</span> 95</td>
<td><span class="math inline">\(x_{2,1} =\)</span>nonchilled</td>
</tr>
<tr class="even">
<td><span class="math inline">\(y_1 =\)</span> 30.4</td>
<td><span class="math inline">\(x_{1,2} =\)</span> 175</td>
<td><span class="math inline">\(x_{2,2} =\)</span>nonchilled</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(y_1 =\)</span> 34.8</td>
<td><span class="math inline">\(x_{1,3} =\)</span> 250</td>
<td><span class="math inline">\(x_{2,3} =\)</span>nonchilled</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(y_1 =\)</span> 19.9</td>
<td><span class="math inline">\(x_{1,84} =\)</span> 1000</td>
<td><span class="math inline">\(x_{2,84} =\)</span>chilled</td>
</tr>
</tbody>
</table>
<div id="measuring-location" class="section level5">
<h5><span class="header-section-number">3.2.3.2.1</span> Measuring Location</h5>
<p>Measuring center is important because…</p>
<p>The mean of the <code>uptake</code> variable can be calculated to help summarize the center of the <code>uptake</code> variable’s distribution.</p>
<p>The sample mean is then simply the sum of these values divided by the total number:</p>
<p><span class="math display">\[\bar{y} = \frac{1}{n} \sum_{i=1}^{n} y_i = \frac{1}{84}\sum_{i=1}^{84}y_i = \frac{1}{84}\left(16.0 + 30.4 + 34.8 + ... + 19.9\right)\]</span></p>
<p>This comes out to be 27.21. This value represents one measure of the center or middle of the <code>uptake</code> variable’s distribution.</p>
<p>As the actual data values are used in this calculation, one or two very large or small numbers can have a large influence on the value of the sample mean. To counter this, you can calculate a more robust measure called a <strong>trimmed mean</strong>. This involves removing the highest and lowest values and then calculating the mean with the remaining values. For instance, a 5% trimmed mean drops the lowest and highest 5% of data values and then finds the mean with the remaining values.<br />
Here 0.05*84 = 4.2. This means we should drop off the lowest four and highest four values and then calculate the mean with the remaining 76 values. The 5% trimmed mean comes out to be 27.25. This is another measure of the center of the <code>uptake</code> variable’s distribution.</p>
<p>Another common measure of center is the median. The median involves sorting the data from largest to smallest and reporting the middle value (if there is an odd number of data points) or the average of the two middle values (if there is an even number of data points). You may notice that having very large or small values in the data set do not matter as much for calculation of the median. The largest value for <code>uptake</code> could be replaced by 10000 and the median wouldn’t change. For this reason, the median is also referred to as a robust estimate of the center of the <code>uptake</code> variable’s distribution. The value of the median here is 28.3.</p>
<p>Other measures of location are quantiles or percentiles of the distribution.</p>
<p>Explanation…
Q1, Median, Q3
Examples…</p>
<p>Min and max too</p>
<p>Usually want summaries for different <strong>subgroups of data</strong></p>
<ul>
<li>Ex: Get similar uptake summaries for each <strong>Treatment</strong></li>
</ul>
<table>
<thead>
<tr class="header">
<th align="left">Treatment</th>
<th align="right">Avg</th>
<th align="right">Median</th>
<th align="right">SD</th>
<th align="right">Q1</th>
<th align="right">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">nonchilled</td>
<td align="right">30.64</td>
<td align="right">31.3</td>
<td align="right">9.70</td>
<td align="right">26.47</td>
<td align="right">45.5</td>
</tr>
<tr class="even">
<td align="left">chilled</td>
<td align="right">23.78</td>
<td align="right">19.7</td>
<td align="right">10.88</td>
<td align="right">14.53</td>
<td align="right">42.4</td>
</tr>
</tbody>
</table>
<ul>
<li>Ex: Get similar uptake summaries for each <strong>Treatment</strong> and <strong>Concentration</strong></li>
</ul>
<table>
<thead>
<tr class="header">
<th align="left">Treatment</th>
<th align="right">conc</th>
<th align="right">Avg</th>
<th align="right">Meidan</th>
<th align="right">SD</th>
<th align="right">Q1</th>
<th align="right">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">nonchilled</td>
<td align="right">95</td>
<td align="right">13.28</td>
<td align="right">12.80</td>
<td align="right">2.40</td>
<td align="right">11.48</td>
<td align="right">16.2</td>
</tr>
<tr class="even">
<td align="left">nonchilled</td>
<td align="right">175</td>
<td align="right">25.12</td>
<td align="right">24.65</td>
<td align="right">5.71</td>
<td align="right">20.05</td>
<td align="right">32.4</td>
</tr>
<tr class="odd">
<td align="left">nonchilled</td>
<td align="right">250</td>
<td align="right">32.47</td>
<td align="right">32.70</td>
<td align="right">5.92</td>
<td align="right">27.30</td>
<td align="right">40.3</td>
</tr>
<tr class="even">
<td align="left">nonchilled</td>
<td align="right">350</td>
<td align="right">35.13</td>
<td align="right">34.50</td>
<td align="right">6.12</td>
<td align="right">30.45</td>
<td align="right">42.1</td>
</tr>
<tr class="odd">
<td align="left">nonchilled</td>
<td align="right">500</td>
<td align="right">35.10</td>
<td align="right">33.85</td>
<td align="right">5.65</td>
<td align="right">31.27</td>
<td align="right">42.9</td>
</tr>
<tr class="even">
<td align="left">nonchilled</td>
<td align="right">675</td>
<td align="right">36.02</td>
<td align="right">35.80</td>
<td align="right">6.34</td>
<td align="right">31.43</td>
<td align="right">43.9</td>
</tr>
<tr class="odd">
<td align="left">nonchilled</td>
<td align="right">1000</td>
<td align="right">37.38</td>
<td align="right">37.60</td>
<td align="right">7.06</td>
<td align="right">32.50</td>
<td align="right">45.5</td>
</tr>
<tr class="even">
<td align="left">chilled</td>
<td align="right">95</td>
<td align="right">11.23</td>
<td align="right">10.55</td>
<td align="right">2.86</td>
<td align="right">9.60</td>
<td align="right">15.1</td>
</tr>
<tr class="odd">
<td align="left">chilled</td>
<td align="right">175</td>
<td align="right">19.45</td>
<td align="right">19.50</td>
<td align="right">5.89</td>
<td align="right">15.68</td>
<td align="right">27.3</td>
</tr>
<tr class="even">
<td align="left">chilled</td>
<td align="right">250</td>
<td align="right">25.28</td>
<td align="right">24.20</td>
<td align="right">10.57</td>
<td align="right">17.95</td>
<td align="right">38.1</td>
</tr>
<tr class="odd">
<td align="left">chilled</td>
<td align="right">350</td>
<td align="right">26.20</td>
<td align="right">26.45</td>
<td align="right">10.83</td>
<td align="right">18.15</td>
<td align="right">38.8</td>
</tr>
<tr class="even">
<td align="left">chilled</td>
<td align="right">500</td>
<td align="right">26.65</td>
<td align="right">26.00</td>
<td align="right">11.45</td>
<td align="right">18.30</td>
<td align="right">38.9</td>
</tr>
<tr class="odd">
<td align="left">chilled</td>
<td align="right">675</td>
<td align="right">27.88</td>
<td align="right">28.80</td>
<td align="right">10.96</td>
<td align="right">19.72</td>
<td align="right">39.6</td>
</tr>
<tr class="even">
<td align="left">chilled</td>
<td align="right">1000</td>
<td align="right">29.78</td>
<td align="right">30.30</td>
<td align="right">12.41</td>
<td align="right">20.40</td>
<td align="right">42.4</td>
</tr>
</tbody>
</table>
</div>
<div id="measuring-spread" class="section level5">
<h5><span class="header-section-number">3.2.3.2.2</span> Measuring Spread</h5>
<p>Why do we care…</p>
<p>The most common measure of spread is the <strong>standard deviation</strong> or <strong>variance</strong>.</p>
<p>116.9515132
10.8144123</p>
<p>19.225</p>
</div>
</div>
<div id="measures-a-linear-relationship" class="section level4">
<h4><span class="header-section-number">3.2.3.3</span> Measures a Linear Relationship</h4>
<p>Why do we care…</p>
<p>Covariance, Correlation</p>
<pre><code>## [1] 1552.687</code></pre>
<pre><code>## [1] 0.4851774</code></pre>
<p>Should always plot!</p>
<p>Recap of common summaries</p>
</div>
</div>
<div id="graphical-summaries" class="section level3">
<h3><span class="header-section-number">3.2.4</span> Graphical Summaries</h3>
<div id="barplots-for-categorical-data" class="section level4">
<h4><span class="header-section-number">3.2.4.1</span> Barplots for Categorical Data</h4>
<p>Let’s start by graphing categorical variables (variables in which entries are a label or attribute). Recall that the main goal of summarizing categorical variables is to look at counts for each level or combination of levels for the variables in question.</p>
<p>Again, we’ll look at the titanic data set. To visualize a one-way table a simple bargraph can be made.</p>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-247-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>As you can likely tell, this gives a visual of the counts represented by the heights of the bars rather than the raw count of the contingency table.</p>
<p>To visualize a two-way table, a stacked barplot can be created.</p>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-248-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Interpret…</p>
<p>The <strong>side-by-side barplot</strong> can be created as an alternative visual of the two-way table.</p>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-249-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Interp…</p>
<p>Filled barplots also sometimes useful. Here the bars will be stacked and the bars will be standardized to have constant height. This is really useful when there are an equal number of observations (or close to it) in each category on the x-axis (for instance with some Likert scale data surveys).</p>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-250-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Interpret…</p>
<p>Of course, sometimes it is useful to see the same plot across the levels or settings of another variable. The plots below…</p>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-251-1.png" width="75%" style="display: block; margin: auto;" /></p>
</div>
<div id="histograms-and-density-plots" class="section level4">
<h4><span class="header-section-number">3.2.4.2</span> Histograms and Density Plots</h4>
<p>Next we’ll create common plots for numerical variables (variables in which entries are a numerical value where math can be performed). Recall that the main goal of summarizing numerical variables is to describe the shape, center, and spread of the distribution. Generally, this is done using a histogram, boxplot, or, in the case of two numerical variables, scatterplot.</p>
<p>We’ll again look at the carbon dioxide (CO2) uptake data set. Let’s start by creating a histogram. A histogram …</p>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-252-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Interpret…</p>
<p>Issue with histograms is their variability (quick example). Alternative is the kernel smoothed plot. These…</p>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-253-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Interpret…</p>
<p>or</p>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-254-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Interpret…</p>
<p>Plots can easily be overlayed, as long as they are on the same scale.</p>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-255-1.png" width="75%" style="display: block; margin: auto;" /></p>
</div>
<div id="boxplots" class="section level4">
<h4><span class="header-section-number">3.2.4.3</span> Boxplots</h4>
<p>boxplot</p>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-256-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Sometimes it is useful to overlay the data values themselves on a boxplot in order to see the shape of the distribution more clearly.</p>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-257-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Across another variable</p>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-258-1.png" width="75%" style="display: block; margin: auto;" /></p>
</div>
<div id="scatterplots" class="section level4">
<h4><span class="header-section-number">3.2.4.4</span> Scatterplots</h4>
<p>Scatterplots
Below is a scatterplot of the <code>conc</code> and <code>uptake</code> variables.</p>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-259-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Trend lines and correlation on plot</p>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-260-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Using text for the points too</p>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-261-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Across another variable</p>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-262-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Sometimes create amalgamation type graphs. Useful but be careful not to overwhelm the reader.</p>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-263-1.png" width="90%" style="display: block; margin: auto;" /></p>
</div>
</div>
</div>
<div id="suggestions-for-further-readings" class="section level2">
<h2><span class="header-section-number">3.3</span> Suggestions for Further Readings</h2>
<p>Exploratory data analysis R book is pretty great.</p>
</div>
<div id="software-2" class="section level2">
<h2><span class="header-section-number">3.4</span> Software</h2>
<div id="r-2" class="section level3">
<h3><span class="header-section-number">3.4.1</span> R</h3>
<p>Recall the general workflow for programming in R.</p>
<p><img src="img/RWorkFlow.png" width="80%" style="display: block; margin: auto;" /></p>
<p>This section is meant to instruct on how to produce common numerical and graphical summaries in R.</p>
<div id="numerical-summaries-1" class="section level4">
<h4><span class="header-section-number">3.4.1.1</span> Numerical Summaries</h4>
<p>To create numerical summaries in R, you first need to determine the type of data you have. Remember there are two major categories:</p>
<ul>
<li>Categorical (Qualitative) variable - entries are a label or attribute<br />
</li>
<li>Numerical (Quantitative) variable - entries are a numerical value where math can be performed</li>
</ul>
<p>The main goal is to describe the distribution or pattern and frequency with which you observe the variable. For categorical variables, we used contingency tables to describe the count in each category. In R, this is done using the <code>table</code> function.</p>
<p>We’ll recreate the summaries of the titanic dataset (available in the file <code>titanic.csv</code> in the datasets folder or via the web).</p>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb398-1" title="1">titanicData &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;https://www4.stat.ncsu.edu/~online/datasets/titanic.csv&quot;</span>)</a>
<a class="sourceLine" id="cb398-2" title="2">titanicData</a></code></pre></div>
<pre><code>## # A tibble: 1,310 x 14
##   pclass survived name  sex      age sibsp parch ticket  fare cabin embarked
##    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   
## 1      1        1 Alle~ fema~ 29         0     0 24160   211. B5    S       
## 2      1        1 Alli~ male   0.917     1     2 113781  152. C22 ~ S       
## 3      1        0 Alli~ fema~  2         1     2 113781  152. C22 ~ S       
## 4      1        0 Alli~ male  30         1     2 113781  152. C22 ~ S       
## 5      1        0 Alli~ fema~ 25         1     2 113781  152. C22 ~ S       
## # ... with 1,305 more rows, and 3 more variables: boat &lt;chr&gt;, body &lt;dbl&gt;,
## #   home.dest &lt;chr&gt;</code></pre>
<p>Recall the three variables we created tables for were:</p>
<ul>
<li>embarked (where journey started)<br />
</li>
<li>survived (survive or not)<br />
</li>
<li>sex (Male or Female)</li>
</ul>
<p>To create the <strong>one-way contingency tables</strong>, we simply pass the column of interest to the <code>table</code> function.</p>
<div class="sourceCode" id="cb400"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb400-1" title="1"><span class="kw">table</span>(titanicData<span class="op">$</span>embarked)</a></code></pre></div>
<pre><code>## 
##   C   Q   S 
## 270 123 914</code></pre>
<div class="sourceCode" id="cb402"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb402-1" title="1"><span class="kw">table</span>(titanicData<span class="op">$</span>survived)</a></code></pre></div>
<pre><code>## 
##   0   1 
## 809 500</code></pre>
<div class="sourceCode" id="cb404"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb404-1" title="1"><span class="kw">table</span>(titanicData<span class="op">$</span>sex)</a></code></pre></div>
<pre><code>## 
## female   male 
##    466    843</code></pre>
<p>To create a <strong>two-way contingency table</strong>, we can pass the columns of interest from the dataset.</p>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb406-1" title="1"><span class="kw">table</span>(titanicData<span class="op">$</span>survived, titanicData<span class="op">$</span>sex)</a></code></pre></div>
<pre><code>##    
##     female male
##   0    127  682
##   1    339  161</code></pre>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb408-1" title="1"><span class="kw">table</span>(titanicData<span class="op">$</span>survived, titanicData<span class="op">$</span>embarked)</a></code></pre></div>
<pre><code>##    
##       C   Q   S
##   0 120  79 610
##   1 150  44 304</code></pre>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb410-1" title="1"><span class="kw">table</span>(titanicData<span class="op">$</span>sex, titanicData<span class="op">$</span>embarked)</a></code></pre></div>
<pre><code>##         
##            C   Q   S
##   female 113  60 291
##   male   157  63 623</code></pre>
<p>This same process can continue to create an <strong>n-way contingency table</strong>.</p>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb412-1" title="1"><span class="kw">table</span>(titanicData<span class="op">$</span>sex, titanicData<span class="op">$</span>embarked, titanicData<span class="op">$</span>survived)</a></code></pre></div>
<pre><code>## , ,  = 0
## 
##         
##            C   Q   S
##   female  11  23  93
##   male   109  56 517
## 
## , ,  = 1
## 
##         
##            C   Q   S
##   female 102  37 198
##   male    48   7 106</code></pre>
<p>These table objects in R are actually arrays - the extension of a matrix to more than two dimensions.</p>
<div class="sourceCode" id="cb414"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb414-1" title="1">tab &lt;-<span class="st"> </span><span class="kw">table</span>(titanicData<span class="op">$</span>sex, titanicData<span class="op">$</span>embarked, titanicData<span class="op">$</span>survived)</a>
<a class="sourceLine" id="cb414-2" title="2"><span class="kw">str</span>(tab)</a></code></pre></div>
<pre><code>##  &#39;table&#39; int [1:2, 1:3, 1:2] 11 109 23 56 93 517 102 48 37 7 ...
##  - attr(*, &quot;dimnames&quot;)=List of 3
##   ..$ : chr [1:2] &quot;female&quot; &quot;male&quot;
##   ..$ : chr [1:3] &quot;C&quot; &quot;Q&quot; &quot;S&quot;
##   ..$ : chr [1:2] &quot;0&quot; &quot;1&quot;</code></pre>
<p>You can obtain <strong>conditional</strong> bivariate info by supplying an index.</p>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb416-1" title="1"><span class="co">#returns embarked vs survived table for females</span></a>
<a class="sourceLine" id="cb416-2" title="2">tab[<span class="dv">1</span>, , ]</a></code></pre></div>
<pre><code>##    
##       0   1
##   C  11 102
##   Q  23  37
##   S  93 198</code></pre>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb418-1" title="1"><span class="co">#returns embarked vs survived table for males</span></a>
<a class="sourceLine" id="cb418-2" title="2">tab[<span class="dv">2</span>, , ]</a></code></pre></div>
<pre><code>##    
##       0   1
##   C 109  48
##   Q  56   7
##   S 517 106</code></pre>
<div class="sourceCode" id="cb420"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb420-1" title="1"><span class="co">#returns survived vs sex table for embarked &quot;C&quot;</span></a>
<a class="sourceLine" id="cb420-2" title="2">tab[, <span class="dv">1</span>, ]</a></code></pre></div>
<pre><code>##         
##            0   1
##   female  11 102
##   male   109  48</code></pre>
<p>We can also obtain <strong>conditional</strong> univariate info too!</p>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb422-1" title="1"><span class="co">#Survived status for males that embarked at &quot;Q&quot;</span></a>
<a class="sourceLine" id="cb422-2" title="2">tab[<span class="dv">2</span>, <span class="dv">2</span>, ]</a></code></pre></div>
<pre><code>##  0  1 
## 56  7</code></pre>
<p>For numerical variables, recall that we want to describe the shape, center, and spread of the variable’s distribution.</p>
<p>Recall the carbon dioxide (CO2) uptake data set</p>
<ul>
<li>Response recorded: <code>uptake</code> CO2 uptake rates in grass plants<br />
</li>
<li>Environment manipulated: <code>Treatment</code> - chilled/nonchilled<br />
</li>
<li>Ambient CO2 specified and measured: <code>conc</code></li>
</ul>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb424-1" title="1">CO2 &lt;-<span class="st"> </span><span class="kw">tbl_df</span>(CO2)</a>
<a class="sourceLine" id="cb424-2" title="2">CO2</a></code></pre></div>
<pre><code>## # A tibble: 84 x 5
##   Plant Type   Treatment   conc uptake
##   &lt;ord&gt; &lt;fct&gt;  &lt;fct&gt;      &lt;dbl&gt;  &lt;dbl&gt;
## 1 Qn1   Quebec nonchilled    95   16  
## 2 Qn1   Quebec nonchilled   175   30.4
## 3 Qn1   Quebec nonchilled   250   34.8
## 4 Qn1   Quebec nonchilled   350   37.2
## 5 Qn1   Quebec nonchilled   500   35.3
## # ... with 79 more rows</code></pre>
<p>To investigate the center we looked at the mean, trimmed mean, and the median. The <code>mean</code> and <code>median</code> functions handle these. You simply pass the column of interest. To obtain a trimmed mean, you can use the <code>trim</code> argument.</p>
<div class="sourceCode" id="cb426"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb426-1" title="1"><span class="kw">mean</span>(CO2<span class="op">$</span>uptake)</a></code></pre></div>
<pre><code>## [1] 27.2131</code></pre>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb428-1" title="1"><span class="co">#5% trimmed mean</span></a>
<a class="sourceLine" id="cb428-2" title="2"><span class="kw">mean</span>(CO2<span class="op">$</span>uptake, <span class="dt">trim =</span> <span class="fl">0.05</span>) </a></code></pre></div>
<pre><code>## [1] 27.25263</code></pre>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb430-1" title="1"><span class="kw">median</span>(CO2<span class="op">$</span>uptake)</a></code></pre></div>
<pre><code>## [1] 28.3</code></pre>
<p>To obtain measures of spread we can use <code>var</code> and <code>sd</code>. Similarly, we pass the column of interest to these functions.</p>
<div class="sourceCode" id="cb432"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb432-1" title="1"><span class="kw">var</span>(CO2<span class="op">$</span>uptake)</a></code></pre></div>
<pre><code>## [1] 116.9515</code></pre>
<div class="sourceCode" id="cb434"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb434-1" title="1"><span class="kw">sd</span>(CO2<span class="op">$</span>uptake)</a></code></pre></div>
<pre><code>## [1] 10.81441</code></pre>
<p>Quantiles can be found using the <code>quantile</code> function. You pass the column of interest and a vector of probabilities corresponding to the quantiles of interest.</p>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb436-1" title="1"><span class="kw">quantile</span>(CO2<span class="op">$</span>uptake, <span class="dt">probs =</span> <span class="kw">c</span>(<span class="fl">0.1</span>, <span class="fl">0.2</span>))</a></code></pre></div>
<pre><code>##   10%   20% 
## 12.36 15.64</code></pre>
<p>The IQR can be found by passing the <code>IQR</code> function the column of interest.</p>
<div class="sourceCode" id="cb438"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb438-1" title="1"><span class="kw">IQR</span>(CO2<span class="op">$</span>uptake)</a></code></pre></div>
<pre><code>## [1] 19.225</code></pre>
<p>R has some nice functions that return multiple summaries. For instance, the <code>summary</code> function!</p>
<div class="sourceCode" id="cb440"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb440-1" title="1"><span class="co">#quartiles and mean</span></a>
<a class="sourceLine" id="cb440-2" title="2"><span class="kw">summary</span>(CO2<span class="op">$</span>uptake)</a></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    7.70   17.90   28.30   27.21   37.12   45.50</code></pre>
<p>The <code>psych</code> package has a very nice function called <code>describe</code> that provides many summaries about your numerical variables in the dataset as well. Remember you need to install a package if you’ve never used it and then read it in to your current R session using the <code>library</code> or <code>require</code> function.</p>
<div class="sourceCode" id="cb442"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb442-1" title="1"><span class="kw">describe</span>(titanicData)</a></code></pre></div>
<pre><code>##          vars    n  mean    sd median trimmed   mad  min  max range  skew
## pclass      1 1309  2.29  0.84      3    2.37  0.00 1.00    3  2.00 -0.60
## survived    2 1309  0.38  0.49      0    0.35  0.00 0.00    1  1.00  0.49
## name*       3 1309   NaN    NA     NA     NaN    NA  Inf -Inf  -Inf    NA
## sex*        4 1309   NaN    NA     NA     NaN    NA  Inf -Inf  -Inf    NA
## age         5 1046 29.88 14.41     28   29.39 11.86 0.17   80 79.83  0.41
## sibsp       6 1309  0.50  1.04      0    0.27  0.00 0.00    8  8.00  3.84
## parch       7 1309  0.39  0.87      0    0.18  0.00 0.00    9  9.00  3.66
##          kurtosis   se
## pclass      -1.32 0.02
## survived    -1.77 0.01
## name*          NA   NA
## sex*           NA   NA
## age          0.13 0.45
## sibsp       19.93 0.03
## parch       21.42 0.02
##  [ reached &#39;max&#39; / getOption(&quot;max.print&quot;) -- omitted 7 rows ]</code></pre>
<div class="sourceCode" id="cb444"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb444-1" title="1"><span class="kw">describe</span>(CO2)</a></code></pre></div>
<pre><code>##            vars  n   mean     sd median trimmed    mad  min    max range  skew
## Plant*        1 84   6.50   3.47    6.5    6.50   4.45  1.0   12.0  11.0  0.00
## Type*         2 84   1.50   0.50    1.5    1.50   0.74  1.0    2.0   1.0  0.00
## Treatment*    3 84   1.50   0.50    1.5    1.50   0.74  1.0    2.0   1.0  0.00
## conc          4 84 435.00 295.92  350.0  408.53 259.45 95.0 1000.0 905.0  0.72
## uptake        5 84  27.21  10.81   28.3   27.33  14.83  7.7   45.5  37.8 -0.10
##            kurtosis    se
## Plant*        -1.26  0.38
## Type*         -2.02  0.05
## Treatment*    -2.02  0.05
## conc          -0.68 32.29
## uptake        -1.35  1.18</code></pre>
<p>Recall, if you had multiple numerical variables we often want to measure the linear relationship. This is done via covariance and correlation. If you pass the <code>var</code> or <code>cov</code> function a data frame with multiple numeric columns, you’ll obtain the variance-covariance matrix. The diagonals represent the variance and the off-diagonals the covariances. The <code>cor</code> function similarly gives the correlation matrix.</p>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb446-1" title="1"><span class="kw">var</span>(<span class="kw">select</span>(CO2, conc, uptake))</a></code></pre></div>
<pre><code>##             conc    uptake
## conc   87571.084 1552.6867
## uptake  1552.687  116.9515</code></pre>
<div class="sourceCode" id="cb448"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb448-1" title="1"><span class="kw">cov</span>(<span class="kw">select</span>(CO2, conc, uptake))</a></code></pre></div>
<pre><code>##             conc    uptake
## conc   87571.084 1552.6867
## uptake  1552.687  116.9515</code></pre>
<p>Of course, often summaries by a subgroup of the data is of interest. We looked at finding summaries of <code>uptake</code> for each <code>Treatment</code> level. <code>dplyr</code> is easy to use for this purpose but can only use functions that return a single value. The idea is:</p>
<ul>
<li>Use <code>group_by</code> to create subgroups associated with the data frame<br />
</li>
<li>Use <code>summarize</code> to create basic summaries for each subgroup</li>
</ul>
<p>For example:</p>
<div class="sourceCode" id="cb450"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb450-1" title="1">CO2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(Treatment) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb450-2" title="2"><span class="st">    </span><span class="kw">summarise</span>(<span class="dt">avg =</span> <span class="kw">mean</span>(uptake), <span class="dt">med =</span> <span class="kw">median</span>(uptake), <span class="dt">var =</span> <span class="kw">var</span>(uptake))</a></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   Treatment    avg   med   var
##   &lt;fct&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 nonchilled  30.6  31.3  94.2
## 2 chilled     23.8  19.7 118.</code></pre>
<p>To find the summary for different settings of two variables, say <strong>Treatment</strong> and <strong>Concentration</strong>, simply pass more than one categorical variable to <code>group_by</code>.</p>
<div class="sourceCode" id="cb452"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb452-1" title="1">CO2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(Treatment, conc) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb452-2" title="2"><span class="st">        </span><span class="kw">summarise</span>(<span class="dt">avg =</span> <span class="kw">mean</span>(uptake), <span class="dt">med =</span> <span class="kw">median</span>(uptake), <span class="dt">var =</span> <span class="kw">var</span>(uptake))</a></code></pre></div>
<pre><code>## # A tibble: 14 x 5
## # Groups:   Treatment [2]
##    Treatment   conc   avg   med    var
##    &lt;fct&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
##  1 nonchilled    95  13.3  12.8   5.75
##  2 nonchilled   175  25.1  24.6  32.6 
##  3 nonchilled   250  32.5  32.7  35.1 
##  4 nonchilled   350  35.1  34.5  37.4 
##  5 nonchilled   500  35.1  33.8  31.9 
##  6 nonchilled   675  36.0  35.8  40.2 
##  7 nonchilled  1000  37.4  37.6  49.8 
##  8 chilled       95  11.2  10.6   8.18
##  9 chilled      175  19.4  19.5  34.7 
## 10 chilled      250  25.3  24.2 112.  
## 11 chilled      350  26.2  26.4 117.  
## 12 chilled      500  26.6  26   131.  
## 13 chilled      675  27.9  28.8 120.  
## 14 chilled     1000  29.8  30.3 154.</code></pre>
<p>An alternative to using <code>dplyr</code> is to use the built-in <code>aggregate</code> function. This function is more flexible and can be used with functions that return more than one value like <code>summary</code>. Basic use gives a response (<code>x</code>) and a <code>list</code> of variables to group <code>by</code>.</p>
<div class="sourceCode" id="cb454"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb454-1" title="1"><span class="kw">aggregate</span>(<span class="dt">x =</span> CO2<span class="op">$</span>uptake, <span class="dt">by =</span> <span class="kw">list</span>(CO2<span class="op">$</span>Treatment), <span class="dt">FUN =</span> summary)</a></code></pre></div>
<pre><code>##      Group.1   x.Min. x.1st Qu. x.Median   x.Mean x.3rd Qu.   x.Max.
## 1 nonchilled 10.60000  26.47500 31.30000 30.64286  38.70000 45.50000
## 2    chilled  7.70000  14.52500 19.70000 23.78333  34.90000 42.40000</code></pre>
<p>Alternatively, <code>formula</code> notation can be used. We can supply <code>uptake ~ Treatment</code> and the data object. The idea of formula notation is essentially a shorthand for modeling the left-hand side (uptake here) by the right-hand side (Treatment here). In this case, this implies finding <code>uptake</code> values returned by <code>FUN</code> for the different levels of <code>Treatment</code>.</p>
<div class="sourceCode" id="cb456"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb456-1" title="1"><span class="kw">aggregate</span>(uptake <span class="op">~</span><span class="st"> </span>Treatment, <span class="dt">data =</span> CO2, <span class="dt">FUN =</span> summary)</a></code></pre></div>
<pre><code>##    Treatment uptake.Min. uptake.1st Qu. uptake.Median uptake.Mean
## 1 nonchilled    10.60000       26.47500      31.30000    30.64286
## 2    chilled     7.70000       14.52500      19.70000    23.78333
##   uptake.3rd Qu. uptake.Max.
## 1       38.70000    45.50000
## 2       34.90000    42.40000</code></pre>
<p>A second variable can be given on the right hand side. The summaries will then be found for every combination of the values of the variables on the right hand side. Since <code>conc</code> is only observed at a few levels, this is reasonable here.</p>
<div class="sourceCode" id="cb458"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb458-1" title="1"><span class="kw">aggregate</span>(uptake <span class="op">~</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>conc, <span class="dt">data =</span> CO2, <span class="dt">FUN =</span> summary)</a></code></pre></div>
<pre><code>##     Treatment conc uptake.Min. uptake.1st Qu. uptake.Median uptake.Mean
## 1  nonchilled   95    10.60000       11.47500      12.80000    13.28333
## 2     chilled   95     7.70000        9.60000      10.55000    11.23333
## 3  nonchilled  175    19.20000       20.05000      24.65000    25.11667
## 4     chilled  175    11.40000       15.67500      19.50000    19.45000
## 5  nonchilled  250    25.80000       27.30000      32.70000    32.46667
## 6     chilled  250    12.30000       17.95000      24.20000    25.28333
## 7  nonchilled  350    27.90000       30.45000      34.50000    35.13333
## 8     chilled  350    13.00000       18.15000      26.45000    26.20000
## 9  nonchilled  500    28.50000       31.27500      33.85000    35.10000
## 10    chilled  500    12.50000       18.30000      26.00000    26.65000
## 11 nonchilled  675    28.10000       31.42500      35.80000    36.01667
## 12    chilled  675    13.70000       19.72500      28.80000    27.88333
##    uptake.3rd Qu. uptake.Max.
## 1        15.40000    16.20000
## 2        13.30000    15.10000
## 3        29.62500    32.40000
## 4        23.32500    27.30000
## 5        36.52500    40.30000
## 6        33.82500    38.10000
## 7        40.65000    42.10000
## 8        34.45000    38.80000
## 9        39.27500    42.90000
## 10       37.07500    38.90000
## 11       40.85000    43.90000
## 12       36.97500    39.60000
##  [ reached getOption(&quot;max.print&quot;) -- omitted 2 rows ]</code></pre>
</div>
<div id="graphical-summaries-1" class="section level4">
<h4><span class="header-section-number">3.4.1.2</span> Graphical Summaries</h4>
<p>There are three major systems for plotting in R.</p>
<ul>
<li><p>Base R (built-in functions)</p>
<ul>
<li>Use <code>plot</code>, <code>barplot</code>, <code>hist</code>, etc. to start a plot<br />
</li>
<li>Annotate the plot using functions like <code>text</code>, <code>lines</code>, <code>points</code>, etc.</li>
</ul></li>
<li><p>Lattice (not covered here)</p></li>
<li><p>ggplot2 (sort of part of the tidyverse - <a href="https://www.google.com/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=2&amp;cad=rja&amp;uact=8&amp;ved=2ahUKEwjFu_ep-rroAhXnknIEHf13Bq4QFjABegQICBAB&amp;url=https%3A%2F%2Frstudio.com%2Fwp-content%2Fuploads%2F2016%2F11%2Fggplot2-cheatsheet-2.1.pdf&amp;usg=AOvVaw1-6jSR5VfWs7V62OYxtDtG">Cheat Sheet</a>)</p>
<ul>
<li><code>ggplot(data = data_frame)</code> creates a plot instance<br />
</li>
<li>Add “layers” to the system (geoms or stats)</li>
</ul></li>
</ul>
<p>There is a great <a href="https://bookdown.org/rdpeng/exdata/plotting-systems.html">reference book here</a> for plotting in R and general exploratory data analysis!</p>
<p>We’ll start by going through common <code>Base R</code> plotting for both categorical and numerical variables. After that, we’ll cover the same plots using <code>ggplot2</code>.</p>
<div id="base-r-plotting" class="section level5">
<h5><span class="header-section-number">3.4.1.2.1</span> <code>Base R</code> Plotting</h5>
<p>Let’s start by graphing categorical variables (variables in which entries are a label or attribute). Recall that the main goal of summarizing categorical variables is to look at counts for each level or combination of levels for the variables in question.</p>
<p>Again, we’ll look at the titanic data set.</p>
<p>The function to create a barplot in R is <code>barplot</code>. Essentially, we can just input the output from the <code>table</code> function into <code>barplot</code>!</p>
<div class="sourceCode" id="cb460"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb460-1" title="1"><span class="kw">table</span>(titanicData<span class="op">$</span>survived)</a></code></pre></div>
<pre><code>## 
##   0   1 
## 809 500</code></pre>
<div class="sourceCode" id="cb462"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb462-1" title="1"><span class="kw">barplot</span>(<span class="kw">table</span>(titanicData<span class="op">$</span>survived))</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-286-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>To visualize a two-way table, a stacked barplot can be created. Again, we simply pass a two-way table to the <code>barplot</code> function.</p>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb463-1" title="1">twoTable &lt;-<span class="st"> </span><span class="kw">table</span>(titanicData<span class="op">$</span>survived, titanicData<span class="op">$</span>sex)</a></code></pre></div>
<div class="sourceCode" id="cb464"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb464-1" title="1"><span class="kw">barplot</span>(twoTable)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-288-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Of course, a legend is needed. Common arguments to <code>barplot</code> include:</p>
<ul>
<li><code>legend = TRUE</code></li>
<li>`args.legend = list(title = “…”)</li>
</ul>
<div class="sourceCode" id="cb465"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb465-1" title="1"><span class="kw">barplot</span>(twoTable, <span class="dt">legend =</span> <span class="ot">TRUE</span>, <span class="dt">args.legend =</span> <span class="kw">list</span>(<span class="dt">title=</span><span class="st">&quot;Survived&quot;</span>))</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-289-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>To create a <strong>Side-by-side barplot</strong>, simply pass a two-way table to <code>barplot</code> with an additional input of <code>beside = TRUE</code>.</p>
<div class="sourceCode" id="cb466"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb466-1" title="1"><span class="kw">barplot</span>(twoTable, <span class="dt">beside =</span> <span class="ot">TRUE</span>, <span class="dt">legend =</span> <span class="ot">TRUE</span>, <span class="dt">args.legend=</span><span class="kw">list</span>(<span class="dt">title=</span><span class="st">&quot;Survived&quot;</span>))</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-290-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>The legend can be specified more clearly by providing a character vector corresponding to the values of the first variable given to the <code>table</code> function.</p>
<div class="sourceCode" id="cb467"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb467-1" title="1"><span class="kw">barplot</span>(twoTable, <span class="dt">beside =</span> <span class="ot">TRUE</span>, <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;Died&quot;</span>, <span class="st">&quot;Survived&quot;</span>),</a>
<a class="sourceLine" id="cb467-2" title="2">        <span class="dt">args.legend=</span><span class="kw">list</span>(<span class="dt">title=</span><span class="st">&quot;Survived&quot;</span>))</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-291-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>To visualize a three-way table, we essentially want to recreate this plot for each setting of the third variable. This is a little difficult in <code>Base R</code> and will be taken up in the <code>ggplot</code> section.</p>
<p>Next we’ll create common plots for numerical variables (variables in which entries are a numerical value where math can be performed). Recall that the main goal of summarizing numerical variables is to describe the shape, center, and spread of the distribution. Generally, this is done using a histogram, boxplot, or, in the case of two numerical variables, scatterplot.</p>
<p>The general process for creating these plots using <code>Base R</code>:</p>
<ul>
<li><p>Use <code>hist</code>, <code>boxpot</code>, <code>plot</code>, etc. to start a plot</p></li>
<li><p>Annotate the plot using functions like <code>text</code>, <code>lines</code>, <code>points</code>, etc.</p></li>
</ul>
<p>We’ll again look at the carbon dioxide (CO2) uptake data set.</p>
<pre><code>## # A tibble: 84 x 5
##   Plant Type   Treatment   conc uptake
##   &lt;ord&gt; &lt;fct&gt;  &lt;fct&gt;      &lt;dbl&gt;  &lt;dbl&gt;
## 1 Qn1   Quebec nonchilled    95   16  
## 2 Qn1   Quebec nonchilled   175   30.4
## 3 Qn1   Quebec nonchilled   250   34.8
## 4 Qn1   Quebec nonchilled   350   37.2
## 5 Qn1   Quebec nonchilled   500   35.3
## # ... with 79 more rows</code></pre>
<p>The <code>hist</code> function creates a histogram and its main argument is a numeric vector.</p>
<div class="sourceCode" id="cb469"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb469-1" title="1"><span class="kw">hist</span>(CO2<span class="op">$</span>uptake)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-293-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>There are many ways to modify the histogram. Some common things to change would be the title (<code>main</code>), the bin calculation (<code>breaks</code>), and perhaps the color of the bars (<code>col</code>).</p>
<div class="sourceCode" id="cb470"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb470-1" title="1"><span class="kw">hist</span>(CO2<span class="op">$</span>uptake, <span class="dt">main =</span> <span class="st">&quot;Histogram of Uptake Values&quot;</span>, <span class="dt">breaks =</span> <span class="dv">15</span>, <span class="dt">col =</span> <span class="st">&quot;Red&quot;</span>)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-294-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Often there is a value that you’d like to highlight by adding a line. This can be done using the <code>abline</code> function (<code>lty</code> specifies line type, <code>lwd</code> the line width, <code>col</code> the color, etc. - see <code>help(par)</code> for more information). <code>abline</code> will add a line to the most recently created plot.</p>
<div class="sourceCode" id="cb471"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb471-1" title="1"><span class="kw">hist</span>(CO2<span class="op">$</span>uptake, <span class="dt">main =</span> <span class="st">&quot;Histogram of Uptake Values&quot;</span>, <span class="dt">breaks =</span> <span class="dv">15</span>, <span class="dt">col =</span> <span class="st">&quot;Red&quot;</span>)</a>
<a class="sourceLine" id="cb471-2" title="2"><span class="kw">abline</span>(<span class="dt">v =</span> <span class="kw">mean</span>(CO2<span class="op">$</span>uptake), <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;Blue&quot;</span>)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-295-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>A kernel plot (or smoothed histogram plot) can be created by using the <code>plot</code> function on the output created by the <code>density</code> function. <code>density</code> will comput kernel density estimates, by default using the normal distribution for weighting. As with <code>hist</code>, we pass <code>density</code> the numeric vector of interest.</p>
<div class="sourceCode" id="cb472"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb472-1" title="1"><span class="kw">density</span>(CO2<span class="op">$</span>uptake)</a></code></pre></div>
<pre><code>## 
## Call:
##  density.default(x = CO2$uptake)
## 
## Data: CO2$uptake (84 obs.);  Bandwidth &#39;bw&#39; = 4.012
## 
##        x                y            
##  Min.   :-4.337   Min.   :2.286e-05  
##  1st Qu.:11.132   1st Qu.:2.863e-03  
##  Median :26.600   Median :2.125e-02  
##  Mean   :26.600   Mean   :1.615e-02  
##  3rd Qu.:42.068   3rd Qu.:2.649e-02  
##  Max.   :57.537   Max.   :3.095e-02</code></pre>
<div class="sourceCode" id="cb474"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb474-1" title="1"><span class="kw">plot</span>(<span class="kw">density</span>(CO2<span class="op">$</span>uptake), <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">col =</span> <span class="st">&quot;Blue&quot;</span>, <span class="dt">lty =</span> <span class="dv">3</span>)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-296-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>To overlay a kernel smoother on top of a histogram, we first create a histogram and specify <code>freq = FALSE</code> in order to put the histogram on the same scale as a density plot. Then, we use <code>lines</code> instead of <code>plot</code> on the output of the <code>density</code> call. <code>lines</code> is a function similar to <code>abline</code> in that it will overlay a (more general) ‘line’ on the most recently created plot.</p>
<div class="sourceCode" id="cb475"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb475-1" title="1"><span class="kw">hist</span>(CO2<span class="op">$</span>uptake, <span class="dt">main =</span> <span class="st">&quot;Histogram of Uptake Values&quot;</span>, <span class="dt">col =</span> <span class="st">&quot;Red&quot;</span>, <span class="dt">freq =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb475-2" title="2"><span class="kw">lines</span>(<span class="kw">density</span>(CO2<span class="op">$</span>uptake), <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">col =</span> <span class="st">&quot;Blue&quot;</span>, <span class="dt">lty =</span> <span class="dv">3</span>)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-297-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>To create a boxplot, use the <code>boxplot</code> function. We can specify a single numeric vector as the argument. This will create a single boxplot. To create side-by-side boxplots, the formula notation we’ve used before comes in handy! If we want a boxplot of the <code>uptake</code> variable for each level of the <code>Treatment</code> variable, we pass <code>boxplot</code> <code>uptake ~ Treatment</code> and specify the data set being used (<code>main</code> again will change the title).</p>
<div class="sourceCode" id="cb476"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb476-1" title="1"><span class="kw">boxplot</span>(uptake <span class="op">~</span><span class="st"> </span>Treatment, <span class="dt">data =</span> CO2, <span class="dt">main =</span> <span class="st">&quot;Boxplot of Uptake by Treatment&quot;</span>)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-298-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>It is easy to change the orientation using the <code>horizontal</code> argument.</p>
<div class="sourceCode" id="cb477"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb477-1" title="1"><span class="kw">boxplot</span>(uptake <span class="op">~</span><span class="st"> </span>Treatment, <span class="dt">data =</span> CO2, </a>
<a class="sourceLine" id="cb477-2" title="2">        <span class="dt">main =</span> <span class="st">&quot;Boxplot of Uptake by Treatment&quot;</span>, <span class="dt">horizontal =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-299-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Most of the graphical parameters used previously can be changed here too because <code>boxplot</code> has the ellipsis argument <code>...</code>.</p>
<div class="sourceCode" id="cb478"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb478-1" title="1"><span class="kw">boxplot</span>(uptake <span class="op">~</span><span class="st"> </span>Treatment, <span class="dt">data =</span> CO2, </a>
<a class="sourceLine" id="cb478-2" title="2">        <span class="dt">main =</span> <span class="st">&quot;Boxplot of Uptake by Treatment&quot;</span>, <span class="dt">col =</span> <span class="st">&quot;Grey&quot;</span>, <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">lwd =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-300-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>The ellipsis argument exists in many functions including <code>hist</code>, <code>boxplot</code>, <code>abline</code>, <code>lines</code>, and <code>plot</code> This argument means additional arguments not named in the inputs of the function being called can be passed. These arguments may be used by function calls within one of these functions! You can see the code used in each function by running the function with no <code>()</code> after it.</p>
<div class="sourceCode" id="cb479"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb479-1" title="1">read_csv</a></code></pre></div>
<pre><code>## function (file, col_names = TRUE, col_types = NULL, locale = default_locale(), 
##     na = c(&quot;&quot;, &quot;NA&quot;), quoted_na = TRUE, quote = &quot;\&quot;&quot;, comment = &quot;&quot;, 
##     trim_ws = TRUE, skip = 0, n_max = Inf, guess_max = min(1000, 
##         n_max), progress = show_progress(), skip_empty_rows = TRUE) 
## {
##     tokenizer &lt;- tokenizer_csv(na = na, quoted_na = quoted_na, 
##         quote = quote, comment = comment, trim_ws = trim_ws, 
##         skip_empty_rows = skip_empty_rows)
##     read_delimited(file, tokenizer, col_names = col_names, col_types = col_types, 
##         locale = locale, skip = skip, skip_empty_rows = skip_empty_rows, 
##         comment = comment, n_max = n_max, guess_max = guess_max, 
##         progress = progress)
## }
## &lt;bytecode: 0x0000000019b72570&gt;
## &lt;environment: namespace:readr&gt;</code></pre>
<p>Some functions are ‘generic’ such as <code>mean</code> and <code>plot</code>. You need to know which mean or plot method you are trying to get the code. <code>plot.default</code> is the default!</p>
<div class="sourceCode" id="cb481"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb481-1" title="1">plot.default</a></code></pre></div>
<pre><code>## function (x, y = NULL, type = &quot;p&quot;, xlim = NULL, ylim = NULL, 
##     log = &quot;&quot;, main = NULL, sub = NULL, xlab = NULL, ylab = NULL, 
##     ann = par(&quot;ann&quot;), axes = TRUE, frame.plot = axes, panel.first = NULL, 
##     panel.last = NULL, asp = NA, xgap.axis = NA, ygap.axis = NA, 
##     ...) 
## {
##     localAxis &lt;- function(..., col, bg, pch, cex, lty, lwd) Axis(...)
##     localBox &lt;- function(..., col, bg, pch, cex, lty, lwd) box(...)
##     localWindow &lt;- function(..., col, bg, pch, cex, lty, lwd) plot.window(...)
##     localTitle &lt;- function(..., col, bg, pch, cex, lty, lwd) title(...)
##     xlabel &lt;- if (!missing(x)) 
##         deparse(substitute(x))
##     ylabel &lt;- if (!missing(y)) 
##         deparse(substitute(y))
##     xy &lt;- xy.coords(x, y, xlabel, ylabel, log)
##     xlab &lt;- if (is.null(xlab)) 
##         xy$xlab
##     else xlab
##     ylab &lt;- if (is.null(ylab)) 
##         xy$ylab
##     else ylab
##     xlim &lt;- if (is.null(xlim)) 
##         range(xy$x[is.finite(xy$x)])
##     else xlim
##     ylim &lt;- if (is.null(ylim)) 
##         range(xy$y[is.finite(xy$y)])
##     else ylim
##     dev.hold()
##     on.exit(dev.flush())
##     plot.new()
##     localWindow(xlim, ylim, log, asp, ...)
##     panel.first
##     plot.xy(xy, type, ...)
##     panel.last
##     if (axes) {
##         localAxis(if (is.null(y)) 
##             xy$x
##         else x, side = 1, gap.axis = xgap.axis, ...)
##         localAxis(if (is.null(y)) 
##             x
##         else y, side = 2, gap.axis = ygap.axis, ...)
##     }
##     if (frame.plot) 
##         localBox(...)
##     if (ann) 
##         localTitle(main = main, sub = sub, xlab = xlab, ylab = ylab, 
##             ...)
##     invisible()
## }
## &lt;bytecode: 0x000000001a3804b8&gt;
## &lt;environment: namespace:graphics&gt;</code></pre>
<p>Here you can see that some of the functions called by <code>plot.default</code> also have the <code>...</code> argument being used. This is why the arguments like <code>lty</code> and <code>col</code> can be used even though they aren’t always named in the function inputs explicity. When working with <code>Base R</code> graphics, getting to know the graphical parameters (see <code>help(par)</code>) is important!</p>
<p>The <code>plot</code> function itself is very flexible. General use:</p>
<ul>
<li>Call <code>plot</code><br />
</li>
<li>Give coordinates for points to be plotted as <code>x</code> and <code>y</code> (usually)<br />
</li>
<li>Change plot type with <code>type</code><br />
</li>
<li>Change graphical parameters such as line type <code>lty</code>, point type <code>pch</code>, color <code>color</code>, etc.<br />
</li>
<li>Add a legend with <code>legend</code></li>
</ul>
<p>To create a basic scatterplot, just specify two numeric vectors of the same length.</p>
<div class="sourceCode" id="cb483"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb483-1" title="1"><span class="kw">plot</span>(<span class="dt">x =</span> CO2<span class="op">$</span>conc, <span class="dt">y =</span> CO2<span class="op">$</span>uptake) </a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-303-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>By default the <code>plot</code> type is ‘p’ for points but many types of plots can be made by changing the <code>type</code> argument. The labels on the axis can be changed using <code>xlab</code> and <code>ylab</code>, the title with <code>main</code>, the plotting character <code>pch</code>, etc.</p>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb484-1" title="1"><span class="kw">plot</span>(<span class="dt">x =</span> CO2<span class="op">$</span>conc, <span class="dt">y =</span> CO2<span class="op">$</span>uptake, <span class="dt">xlab =</span> <span class="st">&quot;Concentration&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Uptake&quot;</span>,</a>
<a class="sourceLine" id="cb484-2" title="2">     <span class="dt">main =</span> <span class="st">&quot;Scatter Plot of Concentration and Uptake&quot;</span>, <span class="dt">pch =</span> <span class="dv">2</span>,</a>
<a class="sourceLine" id="cb484-3" title="3">     <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="kw">max</span>(CO2<span class="op">$</span>uptake)))</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-304-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>To change the plotting symbol (or color, etc.) based on another variable, create appropriate vectors that match the length of the data. For instance, we can create a <code>symbol</code> column on our data frame that is <code>3</code> if the <code>Treatment</code> is ‘chilled’ and <code>2</code> if not. This symbol column is of course the same length as the data. If we pass the <code>pch</code> argument <code>symbol</code>, <code>plot</code> will assign the plotting character <code>3</code> to chilled observations and <code>2</code> if not.</p>
<div class="sourceCode" id="cb485"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb485-1" title="1">CO2<span class="op">$</span>symbol &lt;-<span class="st"> </span><span class="kw">ifelse</span>(CO2<span class="op">$</span>Treatment <span class="op">==</span><span class="st"> &quot;chilled&quot;</span>, <span class="dv">3</span>, <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb485-2" title="2"><span class="kw">select</span>(CO2, uptake, Treatment, symbol)</a></code></pre></div>
<pre><code>## # A tibble: 84 x 3
##   uptake Treatment  symbol
##    &lt;dbl&gt; &lt;fct&gt;       &lt;dbl&gt;
## 1   16   nonchilled      2
## 2   30.4 nonchilled      2
## 3   34.8 nonchilled      2
## 4   37.2 nonchilled      2
## 5   35.3 nonchilled      2
## # ... with 79 more rows</code></pre>
<div class="sourceCode" id="cb487"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb487-1" title="1"><span class="kw">plot</span>(<span class="dt">x =</span> CO2<span class="op">$</span>conc, <span class="dt">y =</span> CO2<span class="op">$</span>uptake, <span class="dt">pch =</span> CO2<span class="op">$</span>symbol)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-305-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>To instruct the reader of the plot, a legend should be added. A manual legend can be created with <code>legend</code>. You can use keywords to specify its location or give an <code>x</code>-<code>y</code> pair. As with the legend for <code>barplot</code>, we can specify the names that display. To match the plot, we should specify the <code>pch</code> corresponding to the levels in the same manner (this would be the same if we changed the color too!).</p>
<div class="sourceCode" id="cb488"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb488-1" title="1"><span class="kw">plot</span>(<span class="dt">x =</span> CO2<span class="op">$</span>conc, <span class="dt">y =</span> CO2<span class="op">$</span>uptake, <span class="dt">pch =</span> CO2<span class="op">$</span>symbol)</a>
<a class="sourceLine" id="cb488-2" title="2"><span class="kw">legend</span>(<span class="dt">x =</span> <span class="dv">810</span>, <span class="dt">y =</span> <span class="dv">18</span>, <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;Chilled&quot;</span>, <span class="st">&quot;Non-Chilled&quot;</span>), <span class="dt">pch =</span> <span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">2</span>))</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-306-1.png" width="75%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb489"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb489-1" title="1"><span class="co">#Note that colors specified as integers come from the `palette` function </span></a>
<a class="sourceLine" id="cb489-2" title="2"><span class="co">#2 is &#39;red&#39; and 3 is &#39;green3&#39;</span></a>
<a class="sourceLine" id="cb489-3" title="3"><span class="kw">plot</span>(<span class="dt">x =</span> CO2<span class="op">$</span>conc, <span class="dt">y =</span> CO2<span class="op">$</span>uptake, <span class="dt">col =</span> CO2<span class="op">$</span>symbol)</a>
<a class="sourceLine" id="cb489-4" title="4"><span class="kw">legend</span>(<span class="dt">x =</span> <span class="dv">810</span>, <span class="dt">y =</span> <span class="dv">18</span>, <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;Chilled&quot;</span>, <span class="st">&quot;Non-Chilled&quot;</span>), <span class="dt">col =</span> <span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">2</span>))</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-306-2.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Plots can be adorned using <code>abline</code>, <code>lines</code>, and <code>text</code> to name a few. For instance, a trend line can be added with <code>abline</code>. We’ll use <code>lm</code> and our formula notation to fit a simple linear regression model (covered later) and <code>abline</code> knows how to plot an object of class <code>lm</code>.</p>
<div class="sourceCode" id="cb490"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb490-1" title="1"><span class="kw">plot</span>(<span class="dt">x =</span> CO2<span class="op">$</span>conc, <span class="dt">y =</span> CO2<span class="op">$</span>uptake, <span class="dt">xlab =</span> <span class="st">&quot;Concentration&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Uptake&quot;</span>,</a>
<a class="sourceLine" id="cb490-2" title="2">     <span class="dt">main =</span> <span class="st">&quot;Scatter Plot of Concentration and Uptake&quot;</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="kw">max</span>(CO2<span class="op">$</span>uptake)))</a>
<a class="sourceLine" id="cb490-3" title="3"><span class="kw">abline</span>(<span class="kw">lm</span>(uptake <span class="op">~</span><span class="st"> </span>conc, <span class="dt">data =</span> CO2), <span class="dt">lwd =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;Blue&quot;</span>)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-307-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>When adding text, the <code>text</code> function can be used. <code>paste</code> or <code>paste0</code> can come in handy. These functions ‘paste’ together strings. <code>paste</code> allows the user to specify the character that separates the pasted together strings and <code>paste0</code> is a special case where there is no separating character.</p>
<div class="sourceCode" id="cb491"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb491-1" title="1"><span class="kw">paste</span>(<span class="st">&quot;Hi&quot;</span>, <span class="st">&quot;What&quot;</span>, <span class="st">&quot;Is&quot;</span>, <span class="st">&quot;Going&quot;</span>, <span class="st">&quot;On&quot;</span>, <span class="st">&quot;?&quot;</span>, <span class="dt">sep =</span> <span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;Hi What Is Going On ?&quot;</code></pre>
<div class="sourceCode" id="cb493"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb493-1" title="1"><span class="kw">paste</span>(<span class="st">&quot;Hi&quot;</span>, <span class="st">&quot;What&quot;</span>, <span class="st">&quot;Is&quot;</span>, <span class="st">&quot;Going&quot;</span>, <span class="st">&quot;On&quot;</span>, <span class="st">&quot;?&quot;</span>, <span class="dt">sep =</span> <span class="st">&quot;.&quot;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;Hi.What.Is.Going.On.?&quot;</code></pre>
<div class="sourceCode" id="cb495"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb495-1" title="1"><span class="kw">paste0</span>(<span class="st">&quot;Hi&quot;</span>, <span class="st">&quot;What&quot;</span>, <span class="st">&quot;Is&quot;</span>, <span class="st">&quot;Going&quot;</span>, <span class="st">&quot;On&quot;</span>, <span class="st">&quot;?&quot;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;HiWhatIsGoingOn?&quot;</code></pre>
<p>We can add the correlation value to the plot using <code>text</code> and assigning the <code>x</code>-<code>y</code> coordinate for the value. Here we round the value to two decimal places using <code>round</code>.</p>
<div class="sourceCode" id="cb497"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb497-1" title="1">correlation &lt;-<span class="st"> </span><span class="kw">cor</span>(CO2<span class="op">$</span>conc, CO2<span class="op">$</span>uptake)</a>
<a class="sourceLine" id="cb497-2" title="2"><span class="kw">plot</span>(<span class="dt">x =</span> CO2<span class="op">$</span>conc, <span class="dt">y =</span> CO2<span class="op">$</span>uptake, <span class="dt">xlab =</span> <span class="st">&quot;Concentration&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Uptake&quot;</span>,</a>
<a class="sourceLine" id="cb497-3" title="3">     <span class="dt">main =</span> <span class="st">&quot;Scatter Plot of Concentration and Uptake&quot;</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="kw">max</span>(CO2<span class="op">$</span>uptake)))</a>
<a class="sourceLine" id="cb497-4" title="4"><span class="kw">abline</span>(<span class="kw">lm</span>(uptake <span class="op">~</span><span class="st"> </span>conc, <span class="dt">data =</span> CO2), <span class="dt">lwd =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;Blue&quot;</span>)</a>
<a class="sourceLine" id="cb497-5" title="5"><span class="kw">text</span>(<span class="dt">x =</span> <span class="dv">750</span>, <span class="dt">y =</span> <span class="dv">10</span>, <span class="dt">cex =</span> <span class="dv">2</span>, </a>
<a class="sourceLine" id="cb497-6" title="6">     <span class="dt">label =</span> <span class="kw">paste0</span>(<span class="st">&quot;Correlation = &quot;</span>, <span class="kw">round</span>(correlation, <span class="dv">2</span>)))</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-309-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>To plot character strings instead of points, <code>text</code> can be used after creating an ‘empty’ <code>plot</code> call. <code>plot</code> should be called and the plotting window set, but the values to plot should be <code>NULL</code> (a special object in R used for things that are undefined). Next, call the text function using the usual <code>x</code>-<code>y</code> coordinates along with a <code>label</code> vector the same length as the data. For example, we could plot the <code>Plant</code> for each data point instead of a symbol.</p>
<div class="sourceCode" id="cb498"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb498-1" title="1"><span class="kw">plot</span>(<span class="ot">NULL</span>, <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="kw">min</span>(CO2<span class="op">$</span>conc), <span class="kw">max</span>(CO2<span class="op">$</span>conc)), <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="kw">min</span>(CO2<span class="op">$</span>uptake), <span class="kw">max</span>(CO2<span class="op">$</span>uptake)), </a>
<a class="sourceLine" id="cb498-2" title="2">     <span class="dt">main =</span> <span class="st">&quot;Scatter Plot of Concentration and Uptake&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;Conc&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Uptake&quot;</span>)</a>
<a class="sourceLine" id="cb498-3" title="3"><span class="kw">text</span>(<span class="dt">x =</span> CO2<span class="op">$</span>conc, <span class="dt">y =</span> CO2<span class="op">$</span>uptake, <span class="dt">label =</span> CO2<span class="op">$</span>Plant)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-310-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Note that you could specify a single character value for <code>label</code> and the plot would still work. This is because R ‘recycles’ the value. This is a powerful but dangerous aspect of R.</p>
<div class="sourceCode" id="cb499"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb499-1" title="1"><span class="kw">plot</span>(<span class="ot">NULL</span>, <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="kw">min</span>(CO2<span class="op">$</span>conc), <span class="kw">max</span>(CO2<span class="op">$</span>conc)), <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="kw">min</span>(CO2<span class="op">$</span>uptake), <span class="kw">max</span>(CO2<span class="op">$</span>uptake)), </a>
<a class="sourceLine" id="cb499-2" title="2">     <span class="dt">main =</span> <span class="st">&quot;Scatter Plot of Concentration and Uptake&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;Conc&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Uptake&quot;</span>)</a>
<a class="sourceLine" id="cb499-3" title="3"><span class="kw">text</span>(<span class="dt">x =</span> CO2<span class="op">$</span>conc, <span class="dt">y =</span> CO2<span class="op">$</span>uptake, <span class="dt">label =</span> <span class="st">&quot;S&quot;</span>)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-311-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>The last <code>Base R</code> plot functionality we’ll mention is the <code>pairs</code> function. This function creates basic plots for all pairs of variables when given a data frame.</p>
<div class="sourceCode" id="cb500"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb500-1" title="1"><span class="kw">pairs</span>(iris[, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>])</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-312-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>To recap <code>Base R</code> plotting:</p>
<ul>
<li><p>Barplot (<code>barplot</code> on a <code>table</code> object)</p></li>
<li><p>Histogram (<code>hist</code>), Density (<code>plot(density)</code> or <code>lines(density)</code>)</p></li>
<li><p>Boxplot (<code>boxplot</code>)</p></li>
<li><p>Scatter plot (<code>plot</code>)</p></li>
<li><p>Useful functions: <code>lines</code>, <code>abline</code>, <code>points</code>, <code>text</code></p></li>
<li><p>Graphical parameters: <code>lty</code>, <code>lwd</code>, <code>pch</code>, <code>cex</code>, <code>color</code></p></li>
</ul>
<p><code>Base R</code> creates superb plots. The main issue is that much of the plotting customizations have to be manually created. It is also a bit more work to create the same plot for each level of another variable. <code>ggplot</code> will automate these processes.</p>
</div>
<div id="ggplot-plotting" class="section level5">
<h5><span class="header-section-number">3.4.1.2.2</span> <code>ggplot</code> Plotting</h5>
<p>Now that we’ve covered <code>Base R</code> plotting, we’ll look at plotting through <code>ggplot2</code> (sort of part of the tidyverse - <a href="https://www.google.com/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=2&amp;cad=rja&amp;uact=8&amp;ved=2ahUKEwjFu_ep-rroAhXnknIEHf13Bq4QFjABegQICBAB&amp;url=https%3A%2F%2Frstudio.com%2Fwp-content%2Fuploads%2F2016%2F11%2Fggplot2-cheatsheet-2.1.pdf&amp;usg=AOvVaw1-6jSR5VfWs7V62OYxtDtG">Cheat Sheet</a>). The main idea is outlined below:</p>
<ul>
<li><code>ggplot(data = data_frame)</code> creates a plot instance<br />
</li>
<li>Add “layers” to the system (geoms or stats)
<ul>
<li>Creates a visualization of the data<br />
</li>
</ul></li>
<li>Modify layer “mapping” args (aes)
<ul>
<li>Ex: size, color, and x, y location(s)<br />
</li>
</ul></li>
<li>Coordinate system (mostly use Cartesian plane)<br />
</li>
<li>Optional: Titles, etc.</li>
</ul>
<p>We’ll go through creation of the same plots in the <code>Base R</code> section.</p>
<p>To create a barplot we can use <code>ggplot + geom_bar</code>. To start, we create a base plotting object with <code>ggplot</code>. Here we can specify attributes of the plot in the <code>aes</code> function. For instance, to create a vertical bar chart we can specify the cateogrical variable of interest as <code>x</code>. Let’s do this for the <code>survived</code> variable from the titanic data set. <code>survived</code> is actually stored as a <code>dbl</code> or double in the dataset since it is coded as a 0/1 variable. The plots will look better if we explicity change this as a <code>factor</code> first.</p>
<div class="sourceCode" id="cb501"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb501-1" title="1">titanicData<span class="op">$</span>survived &lt;-<span class="st"> </span><span class="kw">as.factor</span>(titanicData<span class="op">$</span>survived)</a>
<a class="sourceLine" id="cb501-2" title="2"><span class="kw">ggplot</span>(<span class="dt">data =</span> titanicData, <span class="kw">aes</span>(<span class="dt">x =</span> survived))</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-313-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Notice that no plot is made! We haven’t added a <code>geom</code> or <code>stat</code> layer yet. These are generally what you add in order to actually see something created with the plot. The base plotting object just let’s you specify global attributes like what goes on the x-axis. Having the cheat sheet nearby is highly recommend when learning to use <code>ggplot</code>! The <code>geom</code> layer we want to add is <code>geom_bar</code>.</p>
<div class="sourceCode" id="cb502"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb502-1" title="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> titanicData, <span class="kw">aes</span>(<span class="dt">x =</span> survived)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>()</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-314-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>The usual practice is to save the base object and then add to it. For instance:</p>
<div class="sourceCode" id="cb503"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb503-1" title="1">g &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">data =</span> titanicData, <span class="kw">aes</span>(<span class="dt">x =</span> survived))</a>
<a class="sourceLine" id="cb503-2" title="2">g <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>()</a></code></pre></div>
<p>We won’t do this here just to help make the plots as clear as possible.</p>
<p>You may wonder how to modify the plot. <code>aes()</code> defines visual properties of objects in the plot. This is where a lot of the modification occurs. Changing these is similar to changing values of <code>par</code> in <code>Base R</code> plotting. The cheat sheet gives the most commonly used aesthetics arguments for each <code>geom</code>. Under <code>geom_bar</code> we see</p>
<blockquote>
<p><code>d + geom_bar()</code><br />
<code>x, alpha, color, fill, linetype, size, weight</code></p>
</blockquote>
<p>The <code>data</code> and <code>aes</code> values can be set in two ways:</p>
<ul>
<li><p>‘globally’ (for all layers) via the <code>ggplot</code> statement</p></li>
<li><p>‘locally’ (for just that layer) via the <code>geom</code>, <code>stat</code>, etc. layer</p></li>
</ul>
<div class="sourceCode" id="cb504"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb504-1" title="1"><span class="co">#global </span></a>
<a class="sourceLine" id="cb504-2" title="2"><span class="kw">ggplot</span>(<span class="dt">data =</span> titanicData, <span class="kw">aes</span>(<span class="dt">x =</span> survived)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>()</a>
<a class="sourceLine" id="cb504-3" title="3"><span class="co">#local </span></a>
<a class="sourceLine" id="cb504-4" title="4"><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>(<span class="dt">data =</span> titanicData, <span class="kw">aes</span>(<span class="dt">x =</span> survived))</a></code></pre></div>
<p>To set an attribute that doesn’t depend on the data (i.e. <code>color = 'blue'</code>), you generally place these outside of the <code>aes</code>. Usually only aesthetics that need to depend on the data should go in the <code>aes</code> function.</p>
<p>Back to our barplot. We can improve the plot in a number of ways. First, we can remove the <code>NA</code> (missing value) category by using the <code>drop_na</code> function. Here we’ll remove all rows where any of the three variables we are investigating have missing values.</p>
<div class="sourceCode" id="cb505"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb505-1" title="1">titanicData &lt;-<span class="st"> </span>titanicData <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">drop_na</span>(survived, sex, embarked)</a>
<a class="sourceLine" id="cb505-2" title="2">g &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">data =</span> titanicData, <span class="kw">aes</span>(<span class="dt">x =</span> survived))</a>
<a class="sourceLine" id="cb505-3" title="3">g <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>()</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-317-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Next, we can add better labels and a title by adding the appropriate layers (new layers –&gt; see cheat sheet!). The layers we want here are <code>labs</code> to set the title and <code>x</code> (or <code>y</code>) labels. To change the names on the legend we need to look at the <code>scale_x_discrete</code> layer. This is because the <code>aes</code> value’s scale we are trying to modify is ‘x’ and we are doing so for a layer with a ‘discrete’ variable (their word for categorical).</p>
<div class="sourceCode" id="cb506"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb506-1" title="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> titanicData, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">as.character</span>(survived))) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb506-2" title="2"><span class="st">  </span><span class="kw">geom_bar</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb506-3" title="3"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Survival Status&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;Bar Plot of Survival for Titanic Passengers&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb506-4" title="4"><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Died&quot;</span>, <span class="st">&quot;Survived&quot;</span>))</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-318-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>A <strong>stacked barplot</strong> can be created by using the <code>fill</code> aesthetic and the same process.</p>
<ul>
<li>Create base object<br />
</li>
<li>Add geoms<br />
</li>
<li>Use aes to specify aspects of the plot</li>
</ul>
<p>The truly wonderful things about <code>ggplot</code> are the automatic assignment of colors, the creation of legends, and things of that nature for <code>aes</code> elements. This takes a lot of work from the user. Note: the <code>group</code> aestethic does not automatically generate a legend.</p>
<div class="sourceCode" id="cb507"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb507-1" title="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> titanicData, <span class="kw">aes</span>(<span class="dt">x =</span> survived, <span class="dt">fill =</span> sex)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>()</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-319-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Again, we can add custom labels by adding more layers.</p>
<div class="sourceCode" id="cb508"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb508-1" title="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> titanicData, <span class="kw">aes</span>(<span class="dt">x =</span> survived, <span class="dt">fill =</span> sex)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb508-2" title="2"><span class="st">  </span><span class="kw">geom_bar</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb508-3" title="3"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Survival Status&quot;</span>, </a>
<a class="sourceLine" id="cb508-4" title="4">       <span class="dt">title =</span> <span class="st">&quot;Bar Plot of Survival Status for Titanic Passengers&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb508-5" title="5"><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Died&quot;</span>, <span class="st">&quot;Survived&quot;</span>)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb508-6" title="6"><span class="st">  </span><span class="kw">scale_fill_discrete</span>(<span class="dt">name =</span> <span class="st">&quot;Sex&quot;</span>, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Female&quot;</span>,<span class="st">&quot;Male&quot;</span>))</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-320-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Notice the similar adjustment for the scale using <code>scale_*_discrete</code>. For our aestethics, we set <code>aes(x = survived, fill = sex)</code>. This means if we want to change one of those auto-generated scales we should use <code>scale_aes-value_discrete</code>.</p>
<blockquote>
<p><code>scale_x_discrete(labels = c("Died", "Survived"))</code>
<code>scale_fill_discrete(name = "Sex", labels = c("Female","Male"))</code></p>
</blockquote>
<p>To turn the plot we can add the <code>coord_flip</code> layer.</p>
<div class="sourceCode" id="cb509"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb509-1" title="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> titanicData, <span class="kw">aes</span>(<span class="dt">x =</span> survived, <span class="dt">fill =</span> sex)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb509-2" title="2"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Survival Status&quot;</span>, </a>
<a class="sourceLine" id="cb509-3" title="3">       <span class="dt">title =</span> <span class="st">&quot;Bar Plot of Survival Status for Titanic Passengers&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb509-4" title="4"><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Died&quot;</span>, <span class="st">&quot;Survived&quot;</span>)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb509-5" title="5"><span class="st">  </span><span class="kw">scale_fill_discrete</span>(<span class="dt">name =</span> <span class="st">&quot;Sex&quot;</span>, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Female&quot;</span>,<span class="st">&quot;Male&quot;</span>)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb509-6" title="6"><span class="st">  </span><span class="kw">coord_flip</span>()</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-321-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>One thing that can be quite confusing when you are first using the <code>ggplot</code> function is that most geoms have a corresponding stat that can be used instead. For instance, look at the help for <code>geom_bar</code>:</p>
<p><code>geom_bar(mapping = NULL, data = NULL, stat = "count",   position = "stack", ..., width = NULL, binwidth = NULL, na.rm = FALSE,   show.legend = NA, inherit.aes = TRUE)</code></p>
<p>There is a <code>stat = "count"</code> default argument there. An equivalent plot could be create using a <code>stat</code> layer instead.</p>
<div class="sourceCode" id="cb510"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb510-1" title="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> titanicData, <span class="kw">aes</span>(<span class="dt">x =</span> survived, <span class="dt">fill =</span> sex)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>()</a>
<a class="sourceLine" id="cb510-2" title="2"><span class="kw">ggplot</span>(<span class="dt">data =</span> titanicData, <span class="kw">aes</span>(<span class="dt">x =</span> survived, <span class="dt">fill =</span> sex)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_count</span>() </a></code></pre></div>
<p>Sometimes you’ll need to modify the <code>stat</code>. For example, if you have summary data to begin with rather than the raw data, change the stat to <code>identity</code>.</p>
<div class="sourceCode" id="cb511"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb511-1" title="1">sumData &lt;-<span class="st"> </span>titanicData <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(survived, sex) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">count =</span> <span class="kw">n</span>())</a>
<a class="sourceLine" id="cb511-2" title="2"><span class="kw">ggplot</span>(sumData, <span class="kw">aes</span>(<span class="dt">x =</span> survived, <span class="dt">y =</span> count, <span class="dt">fill =</span> sex)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb511-3" title="3"><span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-323-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>The <strong>side-by-side barplot</strong> can be created using the <code>position</code> aesthetic. <code>position</code> has the following values:</p>
<ul>
<li><code>dodge</code> for side-by-side bar plot<br />
</li>
<li><code>jitter</code> for continuous data with many points at same values<br />
</li>
<li><code>fill</code> stacks bars and standardises each stack to have constant height<br />
</li>
<li><code>stack</code> stacks bars on top of each other</li>
</ul>
<p>As the value of this aestethic doesn’t depend on the data, we do not place this argument in the <code>aes</code> function.</p>
<div class="sourceCode" id="cb512"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb512-1" title="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> titanicData, <span class="kw">aes</span>(<span class="dt">x =</span> survived, <span class="dt">fill =</span> sex)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb512-2" title="2"><span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">position =</span> <span class="st">&quot;dodge&quot;</span>)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-324-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>If we use <code>position = fill</code> the bars will be stacked and the bars will be standardized to have constant height. This is really useful when there are an equal number of observations (or close to it) in each category on the x-axis (for instance with some Likert scale data surveys).</p>
<div class="sourceCode" id="cb513"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb513-1" title="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> titanicData, <span class="kw">aes</span>(<span class="dt">x =</span> survived, <span class="dt">fill =</span> sex)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb513-2" title="2"><span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">position =</span> <span class="st">&quot;fill&quot;</span>)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-325-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Where else does <code>ggplot</code> shine? What if we want to make the same type of barplot for each <code>embarked</code> value? Here we can use <strong>faceting</strong>! This is just another layer on the plot call.</p>
<p><code>facet_wrap(~ var)</code> creates a plot for each setting of the variable <code>var</code>. You can specify <code>nrow</code> and <code>ncol</code> or let R figure it out.</p>
<div class="sourceCode" id="cb514"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb514-1" title="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> titanicData, <span class="kw">aes</span>(<span class="dt">x =</span> survived)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb514-2" title="2"><span class="st">  </span><span class="kw">geom_bar</span>(<span class="kw">aes</span>(<span class="dt">fill =</span>sex), <span class="dt">position =</span> <span class="st">&quot;dodge&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb514-3" title="3"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>embarked)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-326-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p><code>facet_grid(var1 ~ var2)</code> creates a grid of plots for each combination of the variables <code>var1</code> and <code>var2</code>. <code>var1</code> values go across rows and <code>var2</code> values go across columns. To have side-by-side or a vertical column of plots use <code>. ~ var2</code> or <code>var1 ~ .</code>, respectively.</p>
<div class="sourceCode" id="cb515"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb515-1" title="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> titanicData, <span class="kw">aes</span>(<span class="dt">x =</span> survived)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb515-2" title="2"><span class="st">  </span><span class="kw">geom_bar</span>(<span class="kw">aes</span>(<span class="dt">fill =</span>sex), <span class="dt">position =</span> <span class="st">&quot;dodge&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb515-3" title="3"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>embarked)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-327-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Here we’ll create a grid of plots for all <code>pclass</code> and <code>embarked</code> combinations (so easy!).</p>
<div class="sourceCode" id="cb516"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb516-1" title="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> titanicData, <span class="kw">aes</span>(<span class="dt">x =</span> survived)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb516-2" title="2"><span class="st">  </span><span class="kw">geom_bar</span>(<span class="kw">aes</span>(<span class="dt">fill =</span>sex), <span class="dt">position =</span> <span class="st">&quot;dodge&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb516-3" title="3"><span class="st">  </span><span class="kw">facet_grid</span>(pclass <span class="op">~</span><span class="st"> </span>embarked)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-328-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Below is a recap of creating a barplot with <code>ggplot</code>:</p>
<ul>
<li><p>Use <code>ggplot(data = ...) + geom_bar(aes(x = ...))</code></p></li>
<li><p>With summary data, use <code>geom_bar(stat = identity)</code></p></li>
<li><p>Stacked barplot via <code>aes(fill = )</code></p></li>
<li><p>Side-by-side barplot via <code>position = dodge</code></p></li>
<li><p>Filled barplot via <code>position = fill</code></p></li>
</ul>
<p>Recapping plotting with <code>ggplot</code> so far:</p>
<ul>
<li><p>Can set local or global <code>aes</code></p></li>
<li><p>Modify titles/labels by adding more layers</p></li>
<li><p>Use either stat or geom layer</p></li>
<li><p>Faceting (multiple plots) via <code>facet_grid</code> or <code>facet_wrap</code></p></li>
<li><p>Only need <code>aes</code> if setting a mapping value that is dependent on the data (or you want to create a custom legend!)</p></li>
</ul>
<p>Now we’ll create similar plots to the <code>Base R</code> section for our numeric variables from the <code>CO2</code> uptake dataset. The process is the same:</p>
<ul>
<li>Create base object<br />
</li>
<li>Add geoms<br />
</li>
<li>Use aes to specify aspects of the plot</li>
</ul>
<p>Let’s start by creating a histogram. This can be done with <code>geom_bar</code>. The easiest way to get started with a new <code>geom</code> is to look at the cheat sheet and the common <code>aes</code> values:</p>
<blockquote>
<p><code>c + geom_histogram(binwidth = 5)</code>
<code>x, y, alpha, color, fill, linetype, size, weight</code></p>
</blockquote>
<p>For <code>geom_hist</code>, only <code>x</code> is really needed. Now we’ll create the histogram for the <code>uptake</code> variable.</p>
<div class="sourceCode" id="cb517"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb517-1" title="1">g &lt;-<span class="st"> </span><span class="kw">ggplot</span>(CO2, <span class="kw">aes</span>(<span class="dt">x =</span> uptake))</a>
<a class="sourceLine" id="cb517-2" title="2">g <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>()</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-329-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>We might modify a few attributes of the plot that are not dependent on the data. Remember, these generally are set outside of the <code>aes</code> function.</p>
<div class="sourceCode" id="cb518"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb518-1" title="1">g <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">2</span>, <span class="dt">binwidth =</span> <span class="dv">3</span>)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-330-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>To create the kernel smoother plot (smoothed histogram), we use the <code>geom_density</code> layer. The common <code>aes</code> values from the cheat sheet are:</p>
<blockquote>
<p><code>c + geom_density(kernel = "gaussian")</code></p>
</blockquote>
<blockquote>
<p><code>x, y, alpha, color, fill, group, linetype, size, weight</code></p>
</blockquote>
<p>As with <code>geom_hist</code>, only <code>x =</code> is really needed. The kernel smoother for the <code>uptake</code> variable is created below.</p>
<div class="sourceCode" id="cb519"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb519-1" title="1"><span class="kw">ggplot</span>(CO2, <span class="kw">aes</span>(<span class="dt">x =</span> uptake)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_density</span>()</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-331-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>This is not a pretty plot. The <code>fill</code> aesthetic is usually used with <code>geom_density</code>. Here, we’ll fill by the <code>Treatment</code> variable. We’ll also change the <code>alpha</code> (transparency value, between 0 and 1) and the <code>adjust</code> (modify the kernel density calculations - 0.5 implies half the default bandwidth) aestethics.</p>
<div class="sourceCode" id="cb520"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb520-1" title="1"><span class="kw">ggplot</span>(CO2, <span class="kw">aes</span>(<span class="dt">x =</span> uptake)) <span class="op">+</span></a>
<a class="sourceLine" id="cb520-2" title="2"><span class="st">  </span><span class="kw">geom_density</span>(<span class="dt">adjust =</span> <span class="fl">0.5</span>, <span class="dt">alpha =</span> <span class="fl">0.5</span>, <span class="kw">aes</span>(<span class="dt">fill =</span> Treatment))</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-332-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>We may wish to stack the two density estimates on top of each other. Recall the <code>position</code> aestethic and the choices of <code>dodge</code>, <code>jitter</code>, <code>fill</code>, and <code>stack</code>.</p>
<div class="sourceCode" id="cb521"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb521-1" title="1"><span class="kw">ggplot</span>(CO2, <span class="kw">aes</span>(<span class="dt">x =</span> uptake)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb521-2" title="2"><span class="st">  </span><span class="kw">geom_density</span>(<span class="dt">adjust =</span> <span class="fl">0.5</span>, <span class="dt">alpha =</span> <span class="fl">0.5</span>, <span class="dt">position =</span> <span class="st">&quot;stack&quot;</span>, <span class="kw">aes</span>(<span class="dt">fill =</span> Treatment))</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-333-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Plots can easily be overlayed, as long as they are on the same scale, by simply adding the appropriate layers. To put the histogram on the same scale as a density, we can set <code>y  = ..density..</code> on the <code>geom_hist</code> layer.</p>
<div class="sourceCode" id="cb522"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb522-1" title="1"><span class="kw">ggplot</span>(CO2) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb522-2" title="2"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">y =</span> ..density.., <span class="dt">x =</span> uptake, <span class="dt">fill =</span> Treatment)) <span class="op">+</span></a>
<a class="sourceLine" id="cb522-3" title="3"><span class="st">  </span><span class="kw">geom_density</span>(<span class="dt">adjust =</span> <span class="fl">0.25</span>, <span class="dt">alpha =</span> <span class="fl">0.5</span>, <span class="dt">position =</span> <span class="st">&quot;stack&quot;</span>, </a>
<a class="sourceLine" id="cb522-4" title="4">               <span class="kw">aes</span>(<span class="dt">x =</span> uptake, <span class="dt">fill =</span> Treatment)) </a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-334-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>For these two plots, you can see it is a little beneficial to set global <code>aes()</code> options here. This would allow for an easy change of the <code>fill</code> variable for all layers!</p>
<div class="sourceCode" id="cb523"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb523-1" title="1"><span class="kw">ggplot</span>(CO2, <span class="kw">aes</span>(<span class="dt">x =</span> uptake, <span class="dt">fill =</span> Treatment)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb523-2" title="2"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">y =</span> ..density..)) <span class="op">+</span></a>
<a class="sourceLine" id="cb523-3" title="3"><span class="st">  </span><span class="kw">geom_density</span>(<span class="dt">adjust =</span> <span class="fl">0.25</span>, <span class="dt">alpha =</span> <span class="fl">0.5</span>, <span class="dt">position =</span> <span class="st">&quot;stack&quot;</span>)</a></code></pre></div>
<p>To create a boxplot we can use <code>geom_boxplot</code>. The common <code>aes</code> values from the cheat sheet are:</p>
<blockquote>
<p><code>f + geom_boxplot()</code></p>
</blockquote>
<blockquote>
<p><code>x, y, lower, middle, upper, ymax, ymin, alpha, color, fill, group, linetype, shape, size, weight</code></p>
</blockquote>
<p>For <code>geom_boxplot</code>, only <code>x =, y =</code> are really needed. To create a single vertical boxplot, use <code>x = ""</code>. We’ll create side-by-side boxplots of <code>uptake</code> for each <code>Treatment</code> level.</p>
<div class="sourceCode" id="cb524"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb524-1" title="1">g &lt;-<span class="st"> </span><span class="kw">ggplot</span>(CO2, <span class="kw">aes</span>(<span class="dt">x =</span> Treatment, <span class="dt">y =</span> uptake))</a>
<a class="sourceLine" id="cb524-2" title="2">g <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>(<span class="dt">fill =</span> <span class="st">&quot;grey&quot;</span>)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-336-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Sometimes it is useful to overlay the data values themselves on a boxplot in order to see the shape of the distribution more clearly. This can be done using the <code>geom_jitter</code> layer. The <code>width</code> argument sets how widely the points are scattered (1 = width of box).</p>
<div class="sourceCode" id="cb525"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb525-1" title="1"><span class="kw">ggplot</span>(CO2, <span class="kw">aes</span>(<span class="dt">x =</span> Treatment, <span class="dt">y =</span> uptake)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb525-2" title="2"><span class="st">  </span><span class="kw">geom_boxplot</span>(<span class="dt">fill =</span> <span class="st">&quot;grey&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb525-3" title="3"><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">width =</span> <span class="fl">0.1</span>)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-337-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Note that the order of the layers is important!</p>
<div class="sourceCode" id="cb526"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb526-1" title="1"><span class="kw">ggplot</span>(CO2, <span class="kw">aes</span>(<span class="dt">x =</span> Treatment, <span class="dt">y =</span> uptake)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb526-2" title="2"><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">width =</span> <span class="fl">0.1</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb526-3" title="3"><span class="st">  </span><span class="kw">geom_boxplot</span>(<span class="dt">fill =</span> <span class="st">&quot;grey&quot;</span>)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-338-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>If we wanted to create these same side-by-side boxplots for each value of another variable, we can again use faceting. For instance, we can use <code>facet_wrap</code> with the <code>Type</code> variable.</p>
<div class="sourceCode" id="cb527"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb527-1" title="1"><span class="kw">ggplot</span>(CO2, <span class="kw">aes</span>(<span class="dt">x =</span> Treatment, <span class="dt">y =</span> uptake)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>(<span class="dt">fill =</span> <span class="st">&quot;grey&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb527-2" title="2"><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">width =</span> <span class="fl">0.1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>Type)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-339-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Scatterplots can be created using <code>geom_point</code>. The common <code>aes</code> values from the cheat sheet are:</p>
<blockquote>
<p><code>e + geom_point()</code>
<code>x, y, alpha, color, fill, shape, size, stroke</code></p>
</blockquote>
<p>For <code>geom_point</code>, only <code>x =, y =</code> are really needed.</p>
<p>Below is a scatterplot of the <code>conc</code> and <code>uptake</code> variables.</p>
<div class="sourceCode" id="cb528"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb528-1" title="1">g &lt;-<span class="st"> </span><span class="kw">ggplot</span>(CO2, <span class="kw">aes</span>(<span class="dt">x =</span> conc, <span class="dt">y =</span> uptake)) </a>
<a class="sourceLine" id="cb528-2" title="2">g <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-340-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>A trend lines can be easily added with <code>geom_smooth</code>. The default is a smoothed line. To request the simple linear regression fit, we can use <code>method = lm</code>. Both of these lines are added to the plot below.</p>
<div class="sourceCode" id="cb529"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb529-1" title="1"><span class="kw">ggplot</span>(CO2, <span class="kw">aes</span>(<span class="dt">x =</span> conc, <span class="dt">y =</span> uptake)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st">  </span></a>
<a class="sourceLine" id="cb529-2" title="2"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="kw">aes</span>(<span class="dt">col =</span> <span class="st">&quot;loess&quot;</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb529-3" title="3"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> lm, <span class="kw">aes</span>(<span class="dt">col =</span> <span class="st">&quot;linear&quot;</span>)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb529-4" title="4"><span class="st">  </span><span class="kw">scale_colour_manual</span>(<span class="dt">name =</span> <span class="st">&#39;Smoother&#39;</span>, <span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&#39;loess&#39;</span> =<span class="st"> &#39;purple&#39;</span>, <span class="st">&#39;linear&#39;</span> =<span class="st"> &#39;red&#39;</span>), </a>
<a class="sourceLine" id="cb529-5" title="5">                      <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&#39;GAM&#39;</span>, <span class="st">&#39;Linear&#39;</span>), <span class="dt">guide =</span> <span class="st">&#39;legend&#39;</span>)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-341-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>You may notice something a bit odd in the call above. The value of <code>col</code> (color) was set inside the <code>aes</code> function even though it was not set to a value corresponding to the data set. This is an exception to that rule. If you want to utilize <code>ggplot</code>‘s automatic creation of legends, you can use the method above where labels are given to the color for each line (’loess’ and ‘linear’, respectively). <code>scale_colour_manual</code> is then used to create the legend. Notice the <code>values</code> being set assign colors to the lines here.</p>
<p>Text can also be added to the plot with <code>geom_text</code>. The correlation is added to the plot in a similar way to how it was done in the <code>Base R</code> section. The <code>size</code> argument being set to a value larger than 1 makes the text bigger.</p>
<div class="sourceCode" id="cb530"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb530-1" title="1">correlation &lt;-<span class="st"> </span><span class="kw">cor</span>(CO2<span class="op">$</span>conc, CO2<span class="op">$</span>uptake)</a>
<a class="sourceLine" id="cb530-2" title="2"><span class="kw">ggplot</span>(CO2, <span class="kw">aes</span>(<span class="dt">x =</span> conc, <span class="dt">y =</span> uptake)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb530-3" title="3"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> lm, <span class="dt">col =</span> <span class="st">&quot;Red&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb530-4" title="4"><span class="st">  </span><span class="kw">geom_text</span>(<span class="dt">x =</span> <span class="dv">750</span>, <span class="dt">y =</span> <span class="dv">10</span>, <span class="dt">size =</span> <span class="dv">5</span>, </a>
<a class="sourceLine" id="cb530-5" title="5">            <span class="dt">label =</span> <span class="kw">paste0</span>(<span class="st">&quot;Correlation = &quot;</span>, <span class="kw">round</span>(correlation, <span class="dv">2</span>)))</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-342-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Using text for the points is very easy with <code>geom_text</code>. Just use this layer with a <code>label</code> variable.</p>
<div class="sourceCode" id="cb531"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb531-1" title="1"><span class="kw">ggplot</span>(CO2, <span class="kw">aes</span>(<span class="dt">x =</span> conc, <span class="dt">y =</span> uptake)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb531-2" title="2"><span class="st">  </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">label =</span> Plant))</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-343-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Again, if we want to create similar scatterplots for each value of another variable, we can do so with faceting. (Note: the <code>cut</code> function is very useful for categorizing a numeric variable.) Here we create similar scatterplots for each level of the <code>Treatment</code> variable.</p>
<div class="sourceCode" id="cb532"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb532-1" title="1"><span class="kw">ggplot</span>(CO2, <span class="kw">aes</span>(<span class="dt">x =</span> conc, <span class="dt">y =</span> uptake)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb532-2" title="2"><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">color =</span> Type), <span class="dt">size =</span> <span class="fl">2.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb532-3" title="3"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>Treatment)</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-344-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Lastly, we saw the useful <code>pairs</code> function from <code>Base R</code>. There are many extension packages for <code>ggplot</code> that give great functionality. The <code>GGally</code> package has a function called <code>ggpairs</code> that is similar to pairs but retains the same syntax and functionality of <code>ggplot</code>. Remember to install the package if you haven’t done so and then read it in with the library command (or call the function directly using <code>::</code>).</p>
<div class="sourceCode" id="cb533"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb533-1" title="1"><span class="kw">library</span>(GGally)</a>
<a class="sourceLine" id="cb533-2" title="2"><span class="kw">ggpairs</span>(iris, <span class="kw">aes</span>(<span class="dt">colour =</span> Species, <span class="dt">alpha =</span> <span class="fl">0.4</span>))</a></code></pre></div>
<p><img src="StatisticalMethods_files/figure-html/unnamed-chunk-345-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>To recap numerical variable plots using <code>ggplot</code>, the most common <code>geom</code>s are:</p>
<ul>
<li><p>Histogram (<code>geom_hist</code>), Density (<code>geom_density</code>)</p></li>
<li><p>Boxplot (<code>geom_boxplot</code>)</p></li>
<li><p>Scatter plot (<code>geom_point</code>), Smoothers (<code>geom_smooth</code>)</p></li>
<li><p>Jittered points (<code>geom_jitter</code>)</p></li>
<li><p>Text on plot (<code>geom_text</code>)</p></li>
</ul>
<p>The syntax and functionality of <code>ggplot</code> is recapped below again.</p>
<ul>
<li><p>Can set local or global <code>aes</code></p></li>
<li><p>Modify titles/labels by adding more layers</p></li>
<li><p>Use either stat or geom layer</p></li>
<li><p>Faceting (multiple plots) via <code>facet_grid</code> or <code>facet_wrap</code></p></li>
<li><p>Only need <code>aes</code> if setting a mapping value that is dependent on the data (or you want to create a custom legend!)</p></li>
<li><p>General syntax:</p></li>
</ul>
<p><code>ggplot(data = &lt;DATA&gt;) +</code><br />
  <code>&lt;GEOM_FUNCTION&gt;(mapping = aes(&lt;MAPPINGS&gt;), stat = &lt;STAT&gt;, position = &lt;POSITION&gt;) +</code><br />
  <code>&lt;COORDINATE_FUNCTION&gt; +</code><br />
  <code>&lt;FACET_FUNCTION&gt; +</code><br />
  <code>&lt;LABEL_FUNCTION&gt;</code><br />
<code>)</code></p>
<p>There are many other useful extensions such as <code>gganimate</code>, <code>ggthemes</code>, <code>ggmap</code>, and <code>ggrepel</code>.</p>
</div>
</div>
</div>
<div id="sas-2" class="section level3">
<h3><span class="header-section-number">3.4.2</span> SAS</h3>
<p>This section is meant to instruct on how to produce common numerical and graphical summaries in SAS.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sampling-schemes-and-experimental-design.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="point-estimates.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["StatisticalMethods.pdf", "StatisticalMethods.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
